"""image_astro_cal_done

Revision ID: 887c36dbb427
Revises: a3d5209ebbf4
Create Date: 2023-10-31 13:41:10.158334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887c36dbb427'
down_revision = 'a3d5209ebbf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('astro_cal_done', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'astro_cal_done')
    # ### end Alembic commands ###
