"""catalog_excerpt

Revision ID: a3d5209ebbf4
Revises: 7b0454fbc6ac
Create Date: 2023-10-31 13:32:05.440433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d5209ebbf4'
down_revision = '7b0454fbc6ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_excerpts',
    sa.Column('_format', sa.SMALLINT(), nullable=False),
    sa.Column('_origin', sa.SMALLINT(), nullable=False),
    sa.Column('num_items', sa.Integer(), nullable=False),
    sa.Column('minmag', sa.REAL(), nullable=True),
    sa.Column('maxmag', sa.REAL(), nullable=True),
    sa.Column('filters', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('filepath_extensions', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('md5sum', sa.UUID(), nullable=True),
    sa.Column('md5sum_extensions', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('ra', sa.Double(), nullable=False),
    sa.Column('dec', sa.Double(), nullable=False),
    sa.Column('gallat', sa.Double(), nullable=True),
    sa.Column('gallon', sa.Double(), nullable=True),
    sa.Column('ecllat', sa.Double(), nullable=True),
    sa.Column('ecllon', sa.Double(), nullable=True),
    sa.Column('ra_corner_00', sa.REAL(), nullable=False),
    sa.Column('ra_corner_01', sa.REAL(), nullable=False),
    sa.Column('ra_corner_10', sa.REAL(), nullable=False),
    sa.Column('ra_corner_11', sa.REAL(), nullable=False),
    sa.Column('dec_corner_00', sa.REAL(), nullable=False),
    sa.Column('dec_corner_01', sa.REAL(), nullable=False),
    sa.Column('dec_corner_10', sa.REAL(), nullable=False),
    sa.Column('dec_corner_11', sa.REAL(), nullable=False),
    sa.CheckConstraint('NOT(md5sum IS NULL AND (md5sum_extensions IS NULL OR array_position(md5sum_extensions, NULL) IS NOT NULL))', name='catalog_excerpts_md5sum_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_excerpts__origin'), 'catalog_excerpts', ['_origin'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_created_at'), 'catalog_excerpts', ['created_at'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_dec_corner_00'), 'catalog_excerpts', ['dec_corner_00'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_dec_corner_01'), 'catalog_excerpts', ['dec_corner_01'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_dec_corner_10'), 'catalog_excerpts', ['dec_corner_10'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_dec_corner_11'), 'catalog_excerpts', ['dec_corner_11'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_ecllat'), 'catalog_excerpts', ['ecllat'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_filepath'), 'catalog_excerpts', ['filepath'], unique=True)
    op.create_index(op.f('ix_catalog_excerpts_gallat'), 'catalog_excerpts', ['gallat'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_id'), 'catalog_excerpts', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_maxmag'), 'catalog_excerpts', ['maxmag'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_minmag'), 'catalog_excerpts', ['minmag'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_num_items'), 'catalog_excerpts', ['num_items'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_ra_corner_00'), 'catalog_excerpts', ['ra_corner_00'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_ra_corner_01'), 'catalog_excerpts', ['ra_corner_01'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_ra_corner_10'), 'catalog_excerpts', ['ra_corner_10'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_ra_corner_11'), 'catalog_excerpts', ['ra_corner_11'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_excerpts_ra_corner_11'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_ra_corner_10'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_ra_corner_01'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_ra_corner_00'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_num_items'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_minmag'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_maxmag'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_id'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_gallat'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_filepath'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_ecllat'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_dec_corner_11'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_dec_corner_10'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_dec_corner_01'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_dec_corner_00'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_created_at'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts__origin'), table_name='catalog_excerpts')
    op.drop_table('catalog_excerpts')
    # ### end Alembic commands ###
