"""image_fourcorners

Revision ID: b33a5b72da8b
Revises: e78c1e8bec33
Create Date: 2023-09-07 19:27:39.774329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33a5b72da8b'
down_revision = 'e78c1e8bec33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('ra_corner_00', sa.REAL(), nullable=False))
    op.add_column('images', sa.Column('ra_corner_01', sa.REAL(), nullable=False))
    op.add_column('images', sa.Column('ra_corner_10', sa.REAL(), nullable=False))
    op.add_column('images', sa.Column('ra_corner_11', sa.REAL(), nullable=False))
    op.add_column('images', sa.Column('dec_corner_00', sa.REAL(), nullable=False))
    op.add_column('images', sa.Column('dec_corner_01', sa.REAL(), nullable=False))
    op.add_column('images', sa.Column('dec_corner_10', sa.REAL(), nullable=False))
    op.add_column('images', sa.Column('dec_corner_11', sa.REAL(), nullable=False))
    op.create_index(op.f('ix_images_dec_corner_00'), 'images', ['dec_corner_00'], unique=False)
    op.create_index(op.f('ix_images_dec_corner_01'), 'images', ['dec_corner_01'], unique=False)
    op.create_index(op.f('ix_images_dec_corner_10'), 'images', ['dec_corner_10'], unique=False)
    op.create_index(op.f('ix_images_dec_corner_11'), 'images', ['dec_corner_11'], unique=False)
    op.create_index(op.f('ix_images_ra_corner_00'), 'images', ['ra_corner_00'], unique=False)
    op.create_index(op.f('ix_images_ra_corner_01'), 'images', ['ra_corner_01'], unique=False)
    op.create_index(op.f('ix_images_ra_corner_10'), 'images', ['ra_corner_10'], unique=False)
    op.create_index(op.f('ix_images_ra_corner_11'), 'images', ['ra_corner_11'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_ra_corner_11'), table_name='images')
    op.drop_index(op.f('ix_images_ra_corner_10'), table_name='images')
    op.drop_index(op.f('ix_images_ra_corner_01'), table_name='images')
    op.drop_index(op.f('ix_images_ra_corner_00'), table_name='images')
    op.drop_index(op.f('ix_images_dec_corner_11'), table_name='images')
    op.drop_index(op.f('ix_images_dec_corner_10'), table_name='images')
    op.drop_index(op.f('ix_images_dec_corner_01'), table_name='images')
    op.drop_index(op.f('ix_images_dec_corner_00'), table_name='images')
    op.drop_column('images', 'dec_corner_11')
    op.drop_column('images', 'dec_corner_10')
    op.drop_column('images', 'dec_corner_01')
    op.drop_column('images', 'dec_corner_00')
    op.drop_column('images', 'ra_corner_11')
    op.drop_column('images', 'ra_corner_10')
    op.drop_column('images', 'ra_corner_01')
    op.drop_column('images', 'ra_corner_00')
    # ### end Alembic commands ###
