"""add constraint on md5sum

Revision ID: de8507bd9ff0
Revises: 04e5cdfa1ad9
Create Date: 2023-09-10 11:26:35.072546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8507bd9ff0'
down_revision = '04e5cdfa1ad9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
    # the constraint to limit arrays to not having nulls from: https://stackoverflow.com/a/62166235

    op.create_check_constraint(
        'exposures_md5sum_check',
        'exposures',
        'NOT(md5sum IS NULL AND (md5sum_extensions IS NULL OR array_position(md5sum_extensions, NULL) IS NOT NULL))'
    )
    op.create_check_constraint(
        'images_md5sum_check',
        'images',
        'NOT(md5sum IS NULL AND (md5sum_extensions IS NULL OR array_position(md5sum_extensions, NULL) IS NOT NULL))'
    )
    op.create_check_constraint(
        'sources_list_md5sum_check',
        'source_lists',
        'NOT(md5sum IS NULL AND (md5sum_extensions IS NULL OR array_position(md5sum_extensions, NULL) IS NOT NULL))'
    )
    op.create_check_constraint(
        'cutouts_md5sum_check',
        'cutouts',
        'NOT(md5sum IS NULL AND (md5sum_extensions IS NULL OR array_position(md5sum_extensions, NULL) IS NOT NULL))'
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
    op.drop_constraint('exposures_md5sum_check', 'exposures')
    op.drop_constraint('images_md5sum_check', 'images')
    op.drop_constraint('sources_list_md5sum_check', 'source_lists')
    op.drop_constraint('cutouts_md5sum_check', 'cutouts')
