"""sources_infrad

Revision ID: 406abb705c55
Revises: a9c1d480a229
Create Date: 2023-11-10 15:40:47.568862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406abb705c55'
down_revision = 'a9c1d480a229'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_lists', sa.Column('_inf_aper_num', sa.SMALLINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_lists', '_inf_aper_num')
    # ### end Alembic commands ###
