"""psf

Revision ID: 61b4bf71e1e6
Revises: 8947bfcf3a9a
Create Date: 2023-10-30 22:00:40.028625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b4bf71e1e6'
down_revision = '8947bfcf3a9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psfs',
    sa.Column('_format', sa.SMALLINT(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('fwhm_pixels', sa.REAL(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('filepath_extensions', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('md5sum', sa.UUID(), nullable=True),
    sa.Column('md5sum_extensions', sa.ARRAY(sa.UUID()), nullable=True),
    sa.CheckConstraint('NOT(md5sum IS NULL AND (md5sum_extensions IS NULL OR array_position(md5sum_extensions, NULL) IS NOT NULL))', name='psfs_md5sum_check'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name='psfs_image_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances.id'], name='psfs_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psfs_created_at'), 'psfs', ['created_at'], unique=False)
    op.create_index(op.f('ix_psfs_filepath'), 'psfs', ['filepath'], unique=True)
    op.create_index(op.f('ix_psfs_id'), 'psfs', ['id'], unique=False)
    op.create_index(op.f('ix_psfs_image_id'), 'psfs', ['image_id'], unique=True)
    op.create_index(op.f('ix_psfs_provenance_id'), 'psfs', ['provenance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psfs_provenance_id'), table_name='psfs')
    op.drop_index(op.f('ix_psfs_image_id'), table_name='psfs')
    op.drop_index(op.f('ix_psfs_id'), table_name='psfs')
    op.drop_index(op.f('ix_psfs_filepath'), table_name='psfs')
    op.drop_index(op.f('ix_psfs_created_at'), table_name='psfs')
    op.drop_table('psfs')
    # ### end Alembic commands ###
