"""cascade foreign key deletion on source list

Revision ID: 360a5ebe3848
Revises: f831276c00e2
Create Date: 2023-12-08 11:40:17.861309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360a5ebe3848'
down_revision = 'f831276c00e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('source_lists_image_id_fkey', 'source_lists', type_='foreignkey')
    op.create_foreign_key('source_lists_image_id_fkey', 'source_lists', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('source_lists_image_id_fkey', 'source_lists', type_='foreignkey')
    op.create_foreign_key('source_lists_image_id_fkey', 'source_lists', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###
