"""md5sum_fileondisk

Revision ID: 2e42e5319395
Revises: b90b1e3ec58c
Create Date: 2023-07-18 17:27:22.177269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e42e5319395'
down_revision = 'b90b1e3ec58c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cutouts', sa.Column('md5sum', sa.UUID(), nullable=True))
    op.add_column('cutouts', sa.Column('md5sum_extensions', sa.ARRAY(sa.UUID()), nullable=True))
    op.add_column('exposures', sa.Column('md5sum', sa.UUID(), nullable=True))
    op.add_column('exposures', sa.Column('md5sum_extensions', sa.ARRAY(sa.UUID()), nullable=True))
    op.add_column('images', sa.Column('md5sum', sa.UUID(), nullable=True))
    op.add_column('images', sa.Column('md5sum_extensions', sa.ARRAY(sa.UUID()), nullable=True))
    op.add_column('source_lists', sa.Column('md5sum', sa.UUID(), nullable=True))
    op.add_column('source_lists', sa.Column('md5sum_extensions', sa.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_lists', 'md5sum_extensions')
    op.drop_column('source_lists', 'md5sum')
    op.drop_column('images', 'md5sum_extensions')
    op.drop_column('images', 'md5sum')
    op.drop_column('exposures', 'md5sum_extensions')
    op.drop_column('exposures', 'md5sum')
    op.drop_column('cutouts', 'md5sum_extensions')
    op.drop_column('cutouts', 'md5sum')
    # ### end Alembic commands ###
