"""zp_apercor_in_zeropoint

Revision ID: aae2097b2750
Revises: 406abb705c55
Create Date: 2023-11-13 17:50:40.133739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae2097b2750'
down_revision = '406abb705c55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zero_points', sa.Column('zp', sa.Float(), nullable=False))
    op.add_column('zero_points', sa.Column('dzp', sa.Float(), nullable=False))
    op.add_column('zero_points', sa.Column('aper_cor_radii', sa.ARRAY(sa.REAL()), nullable=True))
    op.add_column('zero_points', sa.Column('aper_cors', sa.ARRAY(sa.REAL()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zero_points', 'aper_cors')
    op.drop_column('zero_points', 'aper_cor_radii')
    op.drop_column('zero_points', 'dzp')
    op.drop_column('zero_points', 'zp')
    # ### end Alembic commands ###
