"""source_list_aper_rads

Revision ID: 8947bfcf3a9a
Revises: 32690eb49d8d
Create Date: 2023-10-25 12:58:26.379512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8947bfcf3a9a'
down_revision = '32690eb49d8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_lists', sa.Column('aper_rads', sa.ARRAY(sa.REAL()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_lists', 'aper_rads')
    # ### end Alembic commands ###
