"""source list and provenance upgrades

Revision ID: e78c1e8bec33
Revises: b90b1e3ec58c
Create Date: 2023-08-01 23:52:47.300666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e78c1e8bec33'
down_revision = '2e42e5319395'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provenances', sa.Column('is_bad', sa.Boolean(), nullable=False))
    op.add_column('provenances', sa.Column('bad_comment', sa.String(), nullable=True))
    op.add_column('provenances', sa.Column('is_outdated', sa.Boolean(), nullable=False))
    op.add_column('provenances', sa.Column('replaced_by', sa.Integer(), nullable=True))
    op.add_column('provenances', sa.Column('is_testing', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'provenances', 'provenances', ['replaced_by'], ['id'], ondelete='SET NULL')
    op.add_column('source_lists', sa.Column('num_sources', sa.Integer(), nullable=False))
    op.drop_column('source_lists', 'is_sub')
    op.create_index(op.f('ix_source_lists_num_sources'), 'source_lists', ['num_sources'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_lists_num_sources'), table_name='source_lists')
    op.drop_column('source_lists', 'num_sources')
    op.add_column('source_lists', sa.Column('is_sub', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'provenances', type_='foreignkey')
    op.drop_column('provenances', 'is_testing')
    op.drop_column('provenances', 'replaced_by')
    op.drop_column('provenances', 'is_outdated')
    op.drop_column('provenances', 'bad_comment')
    op.drop_column('provenances', 'is_bad')
    # ### end Alembic commands ###
