"""wcs source list ondelete cascade

Revision ID: afc54edee946
Revises: 1dc72cec60ad
Create Date: 2023-09-29 20:02:34.730800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc54edee946'
down_revision = '1dc72cec60ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('world_coordinates_source_list_id_fkey', 'world_coordinates', type_='foreignkey')
    op.create_foreign_key('world_coordinates_source_list_id_fkey', 'world_coordinates', 'source_lists', ['source_list_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('zero_points_source_list_id_fkey', 'zero_points', type_='foreignkey')
    op.create_foreign_key('zero_points_source_list_id_fkey', 'zero_points', 'source_lists', ['source_list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('world_coordinates_source_list_id_fkey', 'world_coordinates', type_='foreignkey')
    op.create_foreign_key('world_coordinates_source_list_id_fkey', 'world_coordinates', 'source_lists', ['source_list_id'], ['id'])
    op.drop_constraint('zero_points_source_list_id_fkey', 'zero_points', type_='foreignkey')
    op.create_foreign_key('zero_points_source_list_id_fkey', 'zero_points', 'source_lists', ['source_list_id'], ['id'])
    # ### end Alembic commands ###
