"""source lists to sources

Revision ID: 4c2a7e8a525a
Revises: b53eed9ccb36
Create Date: 2023-12-04 13:07:43.519787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2a7e8a525a'
down_revision = 'b53eed9ccb36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cutouts', sa.Column('sources_id', sa.BigInteger(), nullable=False))
    op.drop_index('ix_cutouts_source_list_id', table_name='cutouts')
    op.create_index(op.f('ix_cutouts_sources_id'), 'cutouts', ['sources_id'], unique=False)
    op.drop_constraint('cutouts_source_list_id_fkey', 'cutouts', type_='foreignkey')
    op.create_foreign_key('cutouts_source_list_id_fkey', 'cutouts', 'source_lists', ['sources_id'], ['id'])
    op.drop_column('cutouts', 'source_list_id')
    op.add_column('world_coordinates', sa.Column('sources_id', sa.BigInteger(), nullable=False))
    op.drop_index('ix_world_coordinates_source_list_id', table_name='world_coordinates')
    op.create_index(op.f('ix_world_coordinates_sources_id'), 'world_coordinates', ['sources_id'], unique=False)
    op.drop_constraint('world_coordinates_source_list_id_fkey', 'world_coordinates', type_='foreignkey')
    op.create_foreign_key('world_coordinates_source_list_id_fkey', 'world_coordinates', 'source_lists', ['sources_id'], ['id'], ondelete='CASCADE')
    op.drop_column('world_coordinates', 'source_list_id')
    op.add_column('zero_points', sa.Column('sources_id', sa.BigInteger(), nullable=False))
    op.drop_index('ix_zero_points_source_list_id', table_name='zero_points')
    op.create_index(op.f('ix_zero_points_sources_id'), 'zero_points', ['sources_id'], unique=False)
    op.drop_constraint('zero_points_source_list_id_fkey', 'zero_points', type_='foreignkey')
    op.create_foreign_key('zero_points_source_list_id_fkey', 'zero_points', 'source_lists', ['sources_id'], ['id'], ondelete='CASCADE')
    op.drop_column('zero_points', 'source_list_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zero_points', sa.Column('source_list_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint('zero_points_source_list_id_fkey', 'zero_points', type_='foreignkey')
    op.create_foreign_key('zero_points_source_list_id_fkey', 'zero_points', 'source_lists', ['source_list_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_zero_points_sources_id'), table_name='zero_points')
    op.create_index('ix_zero_points_source_list_id', 'zero_points', ['source_list_id'], unique=False)
    op.drop_column('zero_points', 'sources_id')
    op.add_column('world_coordinates', sa.Column('source_list_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint('world_coordinates_source_list_id_fkey', 'world_coordinates', type_='foreignkey')
    op.create_foreign_key('world_coordinates_source_list_id_fkey', 'world_coordinates', 'source_lists', ['source_list_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_world_coordinates_sources_id'), table_name='world_coordinates')
    op.create_index('ix_world_coordinates_source_list_id', 'world_coordinates', ['source_list_id'], unique=False)
    op.drop_column('world_coordinates', 'sources_id')
    op.add_column('cutouts', sa.Column('source_list_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint('cutouts_source_list_id_fkey', 'cutouts', type_='foreignkey')
    op.create_foreign_key('cutouts_source_list_id_fkey', 'cutouts', 'source_lists', ['source_list_id'], ['id'])
    op.drop_index(op.f('ix_cutouts_sources_id'), table_name='cutouts')
    op.create_index('ix_cutouts_source_list_id', 'cutouts', ['source_list_id'], unique=False)
    op.drop_column('cutouts', 'sources_id')
    # ### end Alembic commands ###
