"""psf_image_provenance_unique

Revision ID: 7b0454fbc6ac
Revises: 61b4bf71e1e6
Create Date: 2023-11-01 14:10:52.800028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0454fbc6ac'
down_revision = '61b4bf71e1e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_psfs_image_id', table_name='psfs')
    op.create_index(op.f('ix_psfs_image_id'), 'psfs', ['image_id'], unique=False)
    op.create_index('psfs_image_id_provenance_index', 'psfs', ['image_id', 'provenance_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('psfs_image_id_provenance_index', table_name='psfs')
    op.drop_index(op.f('ix_psfs_image_id'), table_name='psfs')
    op.create_index('ix_psfs_image_id', 'psfs', ['image_id'], unique=False)
    # ### end Alembic commands ###
