"""add bitflag to zeropoint

Revision ID: f831276c00e2
Revises: 4c2a7e8a525a
Create Date: 2023-12-06 12:03:29.031978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f831276c00e2'
down_revision = '4c2a7e8a525a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zero_points', sa.Column('_bitflag', sa.BIGINT(), nullable=False))
    op.add_column('zero_points', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('zero_points', sa.Column('_upstream_bitflag', sa.BIGINT(), nullable=False))
    op.create_index(op.f('ix_zero_points__bitflag'), 'zero_points', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_zero_points__upstream_bitflag'), 'zero_points', ['_upstream_bitflag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zero_points__upstream_bitflag'), table_name='zero_points')
    op.drop_index(op.f('ix_zero_points__bitflag'), table_name='zero_points')
    op.drop_column('zero_points', '_upstream_bitflag')
    op.drop_column('zero_points', 'description')
    op.drop_column('zero_points', '_bitflag')
    # ### end Alembic commands ###
