"""calibrator_data_files

Revision ID: 32690eb49d8d
Revises: afc54edee946
Create Date: 2023-09-29 17:34:10.839608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32690eb49d8d'
down_revision = 'afc54edee946'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_files',
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('filepath_extensions', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('md5sum', sa.UUID(), nullable=True),
    sa.Column('md5sum_extensions', sa.ARRAY(sa.UUID()), nullable=True),
    sa.CheckConstraint('NOT(md5sum IS NULL AND md5sum_extensions IS NULL)', name='md5sum_or_md5sum_extensions_check'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances.id'], name='data_files_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_files_created_at'), 'data_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_files_filepath'), 'data_files', ['filepath'], unique=True)
    op.create_index(op.f('ix_data_files_id'), 'data_files', ['id'], unique=False)
    op.create_index(op.f('ix_data_files_provenance_id'), 'data_files', ['provenance_id'], unique=False)
    op.create_table('calibrator_files',
    sa.Column('_type', sa.SMALLINT(), nullable=False),
    sa.Column('_calibrator_set', sa.SMALLINT(), nullable=False),
    sa.Column('_flat_type', sa.SMALLINT(), nullable=True),
    sa.Column('instrument', sa.Text(), nullable=False),
    sa.Column('sensor_section', sa.Text(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=True),
    sa.Column('datafile_id', sa.BigInteger(), nullable=True),
    sa.Column('validity_start', sa.DateTime(), nullable=True),
    sa.Column('validity_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['datafile_id'], ['data_files.id'], name='calibrator_files_data_file_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name='calibrator_files_image_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibrator_files__calibrator_set'), 'calibrator_files', ['_calibrator_set'], unique=False)
    op.create_index(op.f('ix_calibrator_files__flat_type'), 'calibrator_files', ['_flat_type'], unique=False)
    op.create_index(op.f('ix_calibrator_files__type'), 'calibrator_files', ['_type'], unique=False)
    op.create_index(op.f('ix_calibrator_files_created_at'), 'calibrator_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_calibrator_files_datafile_id'), 'calibrator_files', ['datafile_id'], unique=False)
    op.create_index(op.f('ix_calibrator_files_id'), 'calibrator_files', ['id'], unique=False)
    op.create_index(op.f('ix_calibrator_files_image_id'), 'calibrator_files', ['image_id'], unique=False)
    op.create_index(op.f('ix_calibrator_files_instrument'), 'calibrator_files', ['instrument'], unique=False)
    op.create_index(op.f('ix_calibrator_files_sensor_section'), 'calibrator_files', ['sensor_section'], unique=False)
    op.create_index(op.f('ix_calibrator_files_validity_end'), 'calibrator_files', ['validity_end'], unique=False)
    op.create_index(op.f('ix_calibrator_files_validity_start'), 'calibrator_files', ['validity_start'], unique=False)
    op.add_column('images', sa.Column('preproc_bitflag', sa.SMALLINT(), nullable=False))
    op.alter_column('images', 'filter',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'filter',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('images', 'preproc_bitflag')
    op.drop_index(op.f('ix_calibrator_files_validity_start'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files_validity_end'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files_sensor_section'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files_instrument'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files_image_id'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files_id'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files_datafile_id'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files_created_at'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files__type'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files__flat_type'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files__calibrator_set'), table_name='calibrator_files')
    op.drop_table('calibrator_files')
    op.drop_index(op.f('ix_data_files_provenance_id'), table_name='data_files')
    op.drop_index(op.f('ix_data_files_id'), table_name='data_files')
    op.drop_index(op.f('ix_data_files_filepath'), table_name='data_files')
    op.drop_index(op.f('ix_data_files_created_at'), table_name='data_files')
    op.drop_table('data_files')
    # ### end Alembic commands ###
