"""bitflag_exposures_images_source_lists_cutouts

Revision ID: 04e5cdfa1ad9
Revises: af9e2c0aaca3
Create Date: 2023-09-01 11:20:03.589854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e5cdfa1ad9'
down_revision = 'af9e2c0aaca3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cutouts', sa.Column('_bitflag', sa.BIGINT(), nullable=False))
    op.add_column('cutouts', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_cutouts__bitflag'), 'cutouts', ['_bitflag'], unique=False)
    op.add_column('exposures', sa.Column('_bitflag', sa.BIGINT(), nullable=False))
    op.add_column('exposures', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_exposures__bitflag'), 'exposures', ['_bitflag'], unique=False)
    op.add_column('images', sa.Column('_bitflag', sa.BIGINT(), nullable=False))
    op.add_column('images', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_images__bitflag'), 'images', ['_bitflag'], unique=False)
    op.add_column('source_lists', sa.Column('_bitflag', sa.BIGINT(), nullable=False))
    op.add_column('source_lists', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_source_lists__bitflag'), 'source_lists', ['_bitflag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_lists__bitflag'), table_name='source_lists')
    op.drop_column('source_lists', 'description')
    op.drop_column('source_lists', '_bitflag')
    op.drop_index(op.f('ix_images__bitflag'), table_name='images')
    op.drop_column('images', 'description')
    op.drop_column('images', '_bitflag')
    op.drop_index(op.f('ix_exposures__bitflag'), table_name='exposures')
    op.drop_column('exposures', 'description')
    op.drop_column('exposures', '_bitflag')
    op.drop_index(op.f('ix_cutouts__bitflag'), table_name='cutouts')
    op.drop_column('cutouts', 'description')
    op.drop_column('cutouts', '_bitflag')
    # ### end Alembic commands ###
