"""Add is_bad column to Object

Revision ID: 7c7135c678c2
Revises: 2ea9f6f0b790
Create Date: 2024-05-29 19:07:53.364982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7135c678c2'
down_revision = '2ea9f6f0b790'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('is_bad', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'is_bad')
    # ### end Alembic commands ###
