"""deepscore object

Revision ID: 140047012e43
Revises: 147e28b89b99
Create Date: 2024-09-27 21:02:41.467372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '140047012e43'
down_revision = '147e28b89b99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deepscores',
    sa.Column('_algorithm', sa.SMALLINT(), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('measurements_id', sa.UUID(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('score', sa.REAL(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_upstream_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['measurements_id'], ['measurements._id'], name='deepscore_measurements_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='deepscore_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('measurements_id', '_algorithm', 'provenance_id', name='_algorithm_measurements_provenance_uc')
    )
    op.create_index(op.f('ix_deepscores__bitflag'), 'deepscores', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_deepscores__id'), 'deepscores', ['_id'], unique=False)
    op.create_index(op.f('ix_deepscores__upstream_bitflag'), 'deepscores', ['_upstream_bitflag'], unique=False)
    op.create_index(op.f('ix_deepscores_created_at'), 'deepscores', ['created_at'], unique=False)
    op.create_index(op.f('ix_deepscores_measurements_id'), 'deepscores', ['measurements_id'], unique=False)
    op.create_index(op.f('ix_deepscores_provenance_id'), 'deepscores', ['provenance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deepscores_provenance_id'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores_measurements_id'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores_created_at'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores__upstream_bitflag'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores__id'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores__bitflag'), table_name='deepscores')
    op.drop_table('deepscores')
    # ### end Alembic commands ###
