"""Move x and y to measurements

Revision ID: d10a8f2321e2
Revises: a7dde2327dde
Create Date: 2024-06-12 15:37:44.395618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10a8f2321e2'
down_revision = 'a7dde2327dde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cutouts', 'y')
    op.drop_column('cutouts', 'x')
    op.add_column('measurements', sa.Column('x', sa.Integer(), nullable=False))
    op.add_column('measurements', sa.Column('y', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'y')
    op.drop_column('measurements', 'x')
    op.add_column('cutouts', sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cutouts', sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
