"""modify_calibfile_downloadloack

Revision ID: 685ba6bab3f7
Revises: 235bbd00c9c2
Create Date: 2024-06-25 15:18:31.400636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685ba6bab3f7'
down_revision = '235bbd00c9c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calibfile_downloadlock', 'sensor_section',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calibfile_downloadlock', 'sensor_section',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
