"""Move attributes from Cutouts to Measurements

Revision ID: 0905ddadb858
Revises: a7dde2327dde
Create Date: 2024-06-13 18:25:40.361079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0905ddadb858'
down_revision = 'a7dde2327dde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cutouts', 'x')
    op.drop_column('cutouts', 'y')
    op.add_column('measurements', sa.Column('index_in_sources', sa.Integer(), nullable=False))
    op.add_column('measurements', sa.Column('x', sa.Integer(), nullable=False))
    op.add_column('measurements', sa.Column('y', sa.Integer(), nullable=False))
    op.drop_constraint('_measurements_cutouts_provenance_uc', 'measurements', type_='unique')
    op.create_unique_constraint('_measurements_cutouts_provenance_uc', 'measurements', ['cutouts_id', 'index_in_sources', 'provenance_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_measurements_cutouts_provenance_uc', 'measurements', type_='unique')
    op.create_unique_constraint('_measurements_cutouts_provenance_uc', 'measurements', ['cutouts_id', 'provenance_id'])
    op.drop_column('measurements', 'y')
    op.drop_column('measurements', 'x')
    op.drop_column('measurements', 'index_in_sources')
    op.add_column('cutouts', sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cutouts', sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
