"""make WCS a FileOnDiskMixin

Revision ID: 2ea9f6f0b790
Revises: ec64a8fd8cf3
Create Date: 2024-05-22 20:11:31.195961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ea9f6f0b790'
down_revision = '9a4097979249'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('world_coordinates', sa.Column('filepath_extensions', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True))
    op.add_column('world_coordinates', sa.Column('md5sum', sa.UUID(), nullable=True))
    op.add_column('world_coordinates', sa.Column('md5sum_extensions', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True))
    op.add_column('world_coordinates', sa.Column('filepath', sa.Text(), nullable=False))
    op.create_index(op.f('ix_world_coordinates_filepath'), 'world_coordinates', ['filepath'], unique=True)
    op.drop_column('world_coordinates', 'header_excerpt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('world_coordinates', sa.Column('header_excerpt', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_world_coordinates_filepath'), table_name='world_coordinates')
    op.drop_column('world_coordinates', 'filepath')
    op.drop_column('world_coordinates', 'md5sum_extensions')
    op.drop_column('world_coordinates', 'md5sum')
    op.drop_column('world_coordinates', 'filepath_extensions')
    # ### end Alembic commands ###
