"""short filter names

Revision ID: c2071a691bf8
Revises: 147e28b89b99
Create Date: 2024-09-30 17:28:08.770031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2071a691bf8'
down_revision = '147e28b89b99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exposures', sa.Column('_filter', sa.Text(), nullable=True))
    op.drop_index('ix_exposures_filter', table_name='exposures')
    op.create_index(op.f('ix_exposures__filter'), 'exposures', ['_filter'], unique=False)
    op.drop_column('exposures', 'filter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exposures', sa.Column('filter', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_exposures__filter'), table_name='exposures')
    op.create_index('ix_exposures_filter', 'exposures', ['filter'], unique=False)
    op.drop_column('exposures', '_filter')
    # ### end Alembic commands ###
