"""Add is_bad column to Measurements

Revision ID: e56acce98d04
Revises: 7c7135c678c2
Create Date: 2024-05-29 19:16:54.627924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56acce98d04'
down_revision = '7c7135c678c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('is_bad', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'is_bad')
    # ### end Alembic commands ###
