"""deepscore

Revision ID: af06fabdd341
Revises: 685ba6bab3f7
Create Date: 2024-07-31 19:39:37.123013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af06fabdd341'
down_revision = '685ba6bab3f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deepscores',
    sa.Column('_algorithm', sa.SMALLINT(), nullable=False),
    sa.Column('measurements_id', sa.BigInteger(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('score', sa.REAL(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['measurements_id'], ['measurements.id'], name='deep_score_measurements_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances.id'], name='deep_score_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deepscores_created_at'), 'deepscores', ['created_at'], unique=False)
    op.create_index(op.f('ix_deepscores_id'), 'deepscores', ['id'], unique=False)
    op.create_index(op.f('ix_deepscores_measurements_id'), 'deepscores', ['measurements_id'], unique=False)
    op.create_index(op.f('ix_deepscores_provenance_id'), 'deepscores', ['provenance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deepscores_provenance_id'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores_measurements_id'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores_id'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores_created_at'), table_name='deepscores')
    op.drop_table('deepscores')
    # ### end Alembic commands ###
