"""authuser

Revision ID: ceec8a848b40
Revises: 7384c6d07485
Create Date: 2024-06-10 17:52:28.527093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ceec8a848b40'
down_revision = '7384c6d07485'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authuser',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('displayname', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('pubkey', sa.Text(), nullable=True),
    sa.Column('privkey', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authuser_created_at'), 'authuser', ['created_at'], unique=False)
    op.create_index(op.f('ix_authuser_email'), 'authuser', ['email'], unique=False)
    op.create_index(op.f('ix_authuser_username'), 'authuser', ['username'], unique=True)
    op.create_table('passwordlink',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userid', sa.UUID(), nullable=True),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['authuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordlink_created_at'), 'passwordlink', ['created_at'], unique=False)
    op.create_index(op.f('ix_passwordlink_userid'), 'passwordlink', ['userid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passwordlink_userid'), table_name='passwordlink')
    op.drop_index(op.f('ix_passwordlink_created_at'), table_name='passwordlink')
    op.drop_table('passwordlink')
    op.drop_index(op.f('ix_authuser_username'), table_name='authuser')
    op.drop_index(op.f('ix_authuser_email'), table_name='authuser')
    op.drop_index(op.f('ix_authuser_created_at'), table_name='authuser')
    op.drop_table('authuser')
    # ### end Alembic commands ###
