"""refset_single_ref_prov

Revision ID: 5a2647d468be
Revises: 9ef3762a6889
Create Date: 2024-12-17 15:29:44.136501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2647d468be'
down_revision = '9ef3762a6889'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refset_provenance_association')
    op.add_column('refs', sa.Column('sources_id', sa.UUID(), nullable=False))
    op.drop_index('ix_refs_filter', table_name='refs')
    op.drop_index('ix_refs_instrument', table_name='refs')
    op.drop_index('ix_refs_section_id', table_name='refs')
    op.drop_index('ix_refs_target', table_name='refs')
    op.create_index(op.f('ix_refs_sources_id'), 'refs', ['sources_id'], unique=False)
    op.create_foreign_key('references_sources_id_fkey', 'refs', 'source_lists', ['sources_id'], ['_id'], ondelete='CASCADE')
    op.drop_column('refs', 'target')
    op.drop_column('refs', 'filter')
    op.drop_column('refs', 'instrument')
    op.drop_column('refs', 'section_id')
    op.add_column('refsets', sa.Column('provenance_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_refsets_provenance_id'), 'refsets', ['provenance_id'], unique=False)
    op.create_foreign_key('refset_provenance_id_fkey', 'refsets', 'provenances', ['provenance_id'], ['_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refset_provenance_id_fkey', 'refsets', type_='foreignkey')
    op.drop_index(op.f('ix_refsets_provenance_id'), table_name='refsets')
    op.drop_column('refsets', 'provenance_id')
    op.add_column('refs', sa.Column('section_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('refs', sa.Column('instrument', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('refs', sa.Column('filter', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('refs', sa.Column('target', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint('references_sources_id_fkey', 'refs', type_='foreignkey')
    op.drop_index(op.f('ix_refs_sources_id'), table_name='refs')
    op.create_index('ix_refs_target', 'refs', ['target'], unique=False)
    op.create_index('ix_refs_section_id', 'refs', ['section_id'], unique=False)
    op.create_index('ix_refs_instrument', 'refs', ['instrument'], unique=False)
    op.create_index('ix_refs_filter', 'refs', ['filter'], unique=False)
    op.drop_column('refs', 'sources_id')
    op.create_table('refset_provenance_association',
    sa.Column('provenance_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='refset_provenances_association_provenance_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refset_id'], ['refsets._id'], name='refsets_provenances_association_refset_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provenance_id', 'refset_id', name='refset_provenance_association_pkey')
    )
    # ### end Alembic commands ###
