"""data types

Revision ID: 3980d2d0e8e4
Revises: fed8777e6807
Create Date: 2024-04-10 12:20:25.982533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3980d2d0e8e4'
down_revision = 'fed8777e6807'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exposures', 'exp_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('images', 'exp_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('images', 'fwhm_estimate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('images', 'zero_point_estimate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('images', 'lim_mag_estimate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('images', 'bkg_mean_estimate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('images', 'bkg_rms_estimate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('measurements', 'flux_psf',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('measurements', 'flux_psf_err',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('measurements', 'flux_apertures',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=postgresql.ARRAY(sa.REAL()),
               existing_nullable=False)
    op.alter_column('measurements', 'flux_apertures_err',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=postgresql.ARRAY(sa.REAL()),
               existing_nullable=False)
    op.alter_column('measurements', 'aper_radii',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=postgresql.ARRAY(sa.REAL()),
               existing_nullable=False)
    op.alter_column('measurements', 'background',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('measurements', 'background_err',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('measurements', 'area_psf',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('measurements', 'area_apertures',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=postgresql.ARRAY(sa.REAL()),
               existing_nullable=False)
    op.alter_column('measurements', 'offset_x',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('measurements', 'offset_y',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('measurements', 'width',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('measurements', 'elongation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('measurements', 'position_angle',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint('objects_name_key', 'objects', type_='unique')
    op.drop_index('ix_objects_name', table_name='objects')
    op.create_index(op.f('ix_objects_name'), 'objects', ['name'], unique=True)
    op.alter_column('sensor_sections', 'read_noise',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('sensor_sections', 'dark_current',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('sensor_sections', 'gain',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('sensor_sections', 'saturation_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('sensor_sections', 'non_linearity_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('zero_points', 'zp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('zero_points', 'dzp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zero_points', 'dzp',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('zero_points', 'zp',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('sensor_sections', 'non_linearity_limit',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('sensor_sections', 'saturation_limit',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('sensor_sections', 'gain',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('sensor_sections', 'dark_current',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('sensor_sections', 'read_noise',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_index(op.f('ix_objects_name'), table_name='objects')
    op.create_index('ix_objects_name', 'objects', ['name'], unique=False)
    op.create_unique_constraint('objects_name_key', 'objects', ['name'])
    op.alter_column('measurements', 'position_angle',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('measurements', 'elongation',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('measurements', 'width',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('measurements', 'offset_y',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('measurements', 'offset_x',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('measurements', 'area_apertures',
               existing_type=postgresql.ARRAY(sa.REAL()),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=False)
    op.alter_column('measurements', 'area_psf',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('measurements', 'background_err',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('measurements', 'background',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('measurements', 'aper_radii',
               existing_type=postgresql.ARRAY(sa.REAL()),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=False)
    op.alter_column('measurements', 'flux_apertures_err',
               existing_type=postgresql.ARRAY(sa.REAL()),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=False)
    op.alter_column('measurements', 'flux_apertures',
               existing_type=postgresql.ARRAY(sa.REAL()),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=False)
    op.alter_column('measurements', 'flux_psf_err',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('measurements', 'flux_psf',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('images', 'bkg_rms_estimate',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('images', 'bkg_mean_estimate',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('images', 'lim_mag_estimate',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('images', 'zero_point_estimate',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('images', 'fwhm_estimate',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('images', 'exp_time',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('exposures', 'exp_time',
               existing_type=sa.REAL(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
