"""gaiadr3_downloadlock

Revision ID: ea3fabd122d4
Revises: 0df35a4a7925
Create Date: 2024-11-12 21:16:44.409194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3fabd122d4'
down_revision = '0df35a4a7925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gaiadr3_downloadlock',
    sa.Column('minra', sa.REAL(), nullable=False),
    sa.Column('maxra', sa.REAL(), nullable=False),
    sa.Column('mindec', sa.REAL(), nullable=False),
    sa.Column('maxdec', sa.REAL(), nullable=False),
    sa.Column('minmag', sa.REAL(), nullable=True),
    sa.Column('maxmag', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_gaiadr3_downloadlock__id'), 'gaiadr3_downloadlock', ['_id'], unique=False)
    op.create_index(op.f('ix_gaiadr3_downloadlock_created_at'), 'gaiadr3_downloadlock', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gaiadr3_downloadlock_created_at'), table_name='gaiadr3_downloadlock')
    op.drop_index(op.f('ix_gaiadr3_downloadlock__id'), table_name='gaiadr3_downloadlock')
    op.drop_table('gaiadr3_downloadlock')
    # ### end Alembic commands ###
