"""calibfile_downloadlock

Revision ID: ec64a8fd8cf3
Revises: 573289f12368
Create Date: 2024-05-09 19:47:36.150101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec64a8fd8cf3'
down_revision = '573289f12368'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibfile_downloadlock',
    sa.Column('_type', sa.SMALLINT(), nullable=False),
    sa.Column('_calibrator_set', sa.SMALLINT(), nullable=False),
    sa.Column('_flat_type', sa.SMALLINT(), nullable=True),
    sa.Column('instrument', sa.Text(), nullable=False),
    sa.Column('sensor_section', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibfile_downloadlock__calibrator_set'), 'calibfile_downloadlock', ['_calibrator_set'], unique=False)
    op.create_index(op.f('ix_calibfile_downloadlock__flat_type'), 'calibfile_downloadlock', ['_flat_type'], unique=False)
    op.create_index(op.f('ix_calibfile_downloadlock__type'), 'calibfile_downloadlock', ['_type'], unique=False)
    op.create_index(op.f('ix_calibfile_downloadlock_created_at'), 'calibfile_downloadlock', ['created_at'], unique=False)
    op.create_index(op.f('ix_calibfile_downloadlock_id'), 'calibfile_downloadlock', ['id'], unique=False)
    op.create_index(op.f('ix_calibfile_downloadlock_instrument'), 'calibfile_downloadlock', ['instrument'], unique=False)
    op.create_index(op.f('ix_calibfile_downloadlock_sensor_section'), 'calibfile_downloadlock', ['sensor_section'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calibfile_downloadlock_sensor_section'), table_name='calibfile_downloadlock')
    op.drop_index(op.f('ix_calibfile_downloadlock_instrument'), table_name='calibfile_downloadlock')
    op.drop_index(op.f('ix_calibfile_downloadlock_id'), table_name='calibfile_downloadlock')
    op.drop_index(op.f('ix_calibfile_downloadlock_created_at'), table_name='calibfile_downloadlock')
    op.drop_index(op.f('ix_calibfile_downloadlock__type'), table_name='calibfile_downloadlock')
    op.drop_index(op.f('ix_calibfile_downloadlock__flat_type'), table_name='calibfile_downloadlock')
    op.drop_index(op.f('ix_calibfile_downloadlock__calibrator_set'), table_name='calibfile_downloadlock')
    op.drop_table('calibfile_downloadlock')
    # ### end Alembic commands ###
