"""provenancetag

Revision ID: 05bb57675701
Revises: d86b7dee2172
Create Date: 2024-07-25 18:51:53.756271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05bb57675701'
down_revision = 'd86b7dee2172'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provenance_tags',
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances.id'], name='provenance_tags_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag', 'provenance_id', name='_provenancetag_prov_tag_uc')
    )
    op.create_index(op.f('ix_provenance_tags_created_at'), 'provenance_tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_provenance_tags_id'), 'provenance_tags', ['id'], unique=False)
    op.create_index(op.f('ix_provenance_tags_provenance_id'), 'provenance_tags', ['provenance_id'], unique=False)
    op.create_index(op.f('ix_provenance_tags_tag'), 'provenance_tags', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provenance_tags_tag'), table_name='provenance_tags')
    op.drop_index(op.f('ix_provenance_tags_provenance_id'), table_name='provenance_tags')
    op.drop_index(op.f('ix_provenance_tags_id'), table_name='provenance_tags')
    op.drop_index(op.f('ix_provenance_tags_created_at'), table_name='provenance_tags')
    op.drop_table('provenance_tags')
    # ### end Alembic commands ###
