"""extension_to_component

Revision ID: a956948a16c4
Revises: 0b82b234331a
Create Date: 2024-12-10 21:59:33.961526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a956948a16c4'
down_revision = '0b82b234331a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backgrounds', sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True))
    op.add_column('backgrounds', sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True))
    op.drop_column('backgrounds', 'md5sum_extensions')
    op.drop_column('backgrounds', 'filepath_extensions')
    op.add_column('catalog_excerpts', sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True))
    op.add_column('catalog_excerpts', sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True))
    op.drop_column('catalog_excerpts', 'md5sum_extensions')
    op.drop_column('catalog_excerpts', 'filepath_extensions')
    op.add_column('cutouts', sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True))
    op.add_column('cutouts', sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True))
    op.drop_column('cutouts', 'md5sum_extensions')
    op.drop_column('cutouts', 'filepath_extensions')
    op.add_column('data_files', sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True))
    op.add_column('data_files', sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True))
    op.drop_column('data_files', 'md5sum_extensions')
    op.drop_column('data_files', 'filepath_extensions')
    op.add_column('exposures', sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True))
    op.add_column('exposures', sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True))
    op.drop_column('exposures', 'md5sum_extensions')
    op.drop_column('exposures', 'filepath_extensions')
    op.add_column('images', sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True))
    op.add_column('images', sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True))
    op.drop_column('images', 'md5sum_extensions')
    op.drop_column('images', 'filepath_extensions')
    op.add_column('psfs', sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True))
    op.add_column('psfs', sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True))
    op.drop_column('psfs', 'md5sum_extensions')
    op.drop_column('psfs', 'filepath_extensions')
    op.add_column('source_lists', sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True))
    op.add_column('source_lists', sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True))
    op.drop_column('source_lists', 'md5sum_extensions')
    op.drop_column('source_lists', 'filepath_extensions')
    op.add_column('world_coordinates', sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True))
    op.add_column('world_coordinates', sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True))
    op.drop_column('world_coordinates', 'md5sum_extensions')
    op.drop_column('world_coordinates', 'filepath_extensions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE -- alembic missed re-adding the constraints that got lost when the columns
    #   above were deleted!  Stick head in sand and choose not to think too hard about this.
    #   In practice, we're not going to be downgrading.

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('world_coordinates', sa.Column('filepath_extensions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('world_coordinates', sa.Column('md5sum_extensions', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_column('world_coordinates', 'md5sum_components')
    op.drop_column('world_coordinates', 'components')
    op.add_column('source_lists', sa.Column('filepath_extensions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('source_lists', sa.Column('md5sum_extensions', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_column('source_lists', 'md5sum_components')
    op.drop_column('source_lists', 'components')
    op.add_column('psfs', sa.Column('filepath_extensions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('psfs', sa.Column('md5sum_extensions', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_column('psfs', 'md5sum_components')
    op.drop_column('psfs', 'components')
    op.add_column('images', sa.Column('filepath_extensions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('md5sum_extensions', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_column('images', 'md5sum_components')
    op.drop_column('images', 'components')
    op.add_column('exposures', sa.Column('filepath_extensions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('exposures', sa.Column('md5sum_extensions', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_column('exposures', 'md5sum_components')
    op.drop_column('exposures', 'components')
    op.add_column('data_files', sa.Column('filepath_extensions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('data_files', sa.Column('md5sum_extensions', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_column('data_files', 'md5sum_components')
    op.drop_column('data_files', 'components')
    op.add_column('cutouts', sa.Column('filepath_extensions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('cutouts', sa.Column('md5sum_extensions', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_column('cutouts', 'md5sum_components')
    op.drop_column('cutouts', 'components')
    op.add_column('catalog_excerpts', sa.Column('filepath_extensions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('catalog_excerpts', sa.Column('md5sum_extensions', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_column('catalog_excerpts', 'md5sum_components')
    op.drop_column('catalog_excerpts', 'components')
    op.add_column('backgrounds', sa.Column('filepath_extensions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('backgrounds', sa.Column('md5sum_extensions', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_column('backgrounds', 'md5sum_components')
    op.drop_column('backgrounds', 'components')
    # ### end Alembic commands ###
