"""short-filter-in-database

Revision ID: 9ef3762a6889
Revises: 23d4754077d1
Create Date: 2024-12-17 20:54:42.083741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef3762a6889'
down_revision = '23d4754077d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exposures', sa.Column('_filter', sa.Text(), nullable=True))
    op.drop_index('ix_exposures_filter', table_name='exposures')
    op.create_index(op.f('ix_exposures__filter'), 'exposures', ['_filter'], unique=False)
    op.drop_column('exposures', 'filter')
    op.create_check_constraint(
        constraint_name='exposures_filter_or_array_check',
        table_name='exposures',
        condition='NOT(_filter IS NULL AND filter_array IS NULL)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exposures', sa.Column('filter', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_exposures__filter'), table_name='exposures')
    op.create_index('ix_exposures_filter', 'exposures', ['filter'], unique=False)
    op.drop_column('exposures', '_filter')
    # ### end Alembic commands ###
