"""Add is_bad col for Objects and Measurements

Revision ID: fb738792f639
Revises: f36d17393be7
Create Date: 2024-05-30 17:40:50.100711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb738792f639'
down_revision = 'f36d17393be7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('is_bad', sa.Boolean(), nullable=False))
    op.add_column('objects', sa.Column('is_bad', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'is_bad')
    op.drop_column('measurements', 'is_bad')
    # ### end Alembic commands ###
