"""conductor

Revision ID: 235bbd00c9c2
Revises: ceec8a848b40
Create Date: 2024-06-13 17:31:25.857888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '235bbd00c9c2'
down_revision = 'ceec8a848b40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelineworkers',
    sa.Column('cluster_id', sa.Text(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=True),
    sa.Column('nexps', sa.SmallInteger(), nullable=False),
    sa.Column('lastheartbeat', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelineworkers_created_at'), 'pipelineworkers', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipelineworkers_id'), 'pipelineworkers', ['id'], unique=False)
    op.create_table('knownexposures',
    sa.Column('instrument', sa.Text(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hold', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('exposure_id', sa.BigInteger(), nullable=True),
    sa.Column('mjd', sa.Double(), nullable=True),
    sa.Column('exp_time', sa.REAL(), nullable=True),
    sa.Column('filter', sa.Text(), nullable=True),
    sa.Column('project', sa.Text(), nullable=True),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('cluster_id', sa.Text(), nullable=True),
    sa.Column('claim_time', sa.DateTime(), nullable=True),
    sa.Column('ra', sa.Double(), nullable=True),
    sa.Column('dec', sa.Double(), nullable=True),
    sa.Column('gallat', sa.Double(), nullable=True),
    sa.Column('gallon', sa.Double(), nullable=True),
    sa.Column('ecllat', sa.Double(), nullable=True),
    sa.Column('ecllon', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['exposure_id'], ['exposures.id'], name='knownexposure_exposure_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knownexposures_created_at'), 'knownexposures', ['created_at'], unique=False)
    op.create_index(op.f('ix_knownexposures_ecllat'), 'knownexposures', ['ecllat'], unique=False)
    op.create_index(op.f('ix_knownexposures_gallat'), 'knownexposures', ['gallat'], unique=False)
    op.create_index(op.f('ix_knownexposures_id'), 'knownexposures', ['id'], unique=False)
    op.create_index(op.f('ix_knownexposures_identifier'), 'knownexposures', ['identifier'], unique=False)
    op.create_index(op.f('ix_knownexposures_instrument'), 'knownexposures', ['instrument'], unique=False)
    op.create_index(op.f('ix_knownexposures_mjd'), 'knownexposures', ['mjd'], unique=False)
    op.create_index('knownexposures_q3c_ang2ipix_idx', 'knownexposures', [sa.text('q3c_ang2ipix(ra, dec)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('knownexposures_q3c_ang2ipix_idx', table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_mjd'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_instrument'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_identifier'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_id'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_gallat'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_ecllat'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_created_at'), table_name='knownexposures')
    op.drop_table('knownexposures')
    op.drop_index(op.f('ix_pipelineworkers_id'), table_name='pipelineworkers')
    op.drop_index(op.f('ix_pipelineworkers_created_at'), table_name='pipelineworkers')
    op.drop_table('pipelineworkers')
    # ### end Alembic commands ###
