"""rename_refs_table

Revision ID: 573289f12368
Revises: 3980d2d0e8e4
Create Date: 2024-05-07 20:15:45.593877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '573289f12368'
down_revision = '3980d2d0e8e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refs',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('filter', sa.Text(), nullable=False),
    sa.Column('section_id', sa.Text(), nullable=False),
    sa.Column('validity_start', sa.DateTime(), nullable=True),
    sa.Column('validity_end', sa.DateTime(), nullable=True),
    sa.Column('is_bad', sa.Boolean(), nullable=False),
    sa.Column('bad_reason', sa.Text(), nullable=True),
    sa.Column('bad_comment', sa.Text(), nullable=True),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name='references_image_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances.id'], name='references_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refs_created_at'), 'refs', ['created_at'], unique=False)
    op.create_index(op.f('ix_refs_filter'), 'refs', ['filter'], unique=False)
    op.create_index(op.f('ix_refs_id'), 'refs', ['id'], unique=False)
    op.create_index(op.f('ix_refs_image_id'), 'refs', ['image_id'], unique=False)
    op.create_index(op.f('ix_refs_provenance_id'), 'refs', ['provenance_id'], unique=False)
    op.create_index(op.f('ix_refs_section_id'), 'refs', ['section_id'], unique=False)
    op.create_index(op.f('ix_refs_target'), 'refs', ['target'], unique=False)
    op.create_index(op.f('ix_refs_validity_end'), 'refs', ['validity_end'], unique=False)
    op.create_index(op.f('ix_refs_validity_start'), 'refs', ['validity_start'], unique=False)
    op.drop_index('ix_references_created_at', table_name='references')
    op.drop_index('ix_references_filter', table_name='references')
    op.drop_index('ix_references_id', table_name='references')
    op.drop_index('ix_references_image_id', table_name='references')
    op.drop_index('ix_references_provenance_id', table_name='references')
    op.drop_index('ix_references_section_id', table_name='references')
    op.drop_index('ix_references_target', table_name='references')
    op.drop_index('ix_references_validity_end', table_name='references')
    op.drop_index('ix_references_validity_start', table_name='references')
    op.drop_table('references')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('references',
    sa.Column('image_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('target', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('filter', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('section_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('validity_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('validity_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_bad', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('bad_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bad_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provenance_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name='references_image_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances.id'], name='references_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='references_pkey')
    )
    op.create_index('ix_references_validity_start', 'references', ['validity_start'], unique=False)
    op.create_index('ix_references_validity_end', 'references', ['validity_end'], unique=False)
    op.create_index('ix_references_target', 'references', ['target'], unique=False)
    op.create_index('ix_references_section_id', 'references', ['section_id'], unique=False)
    op.create_index('ix_references_provenance_id', 'references', ['provenance_id'], unique=False)
    op.create_index('ix_references_image_id', 'references', ['image_id'], unique=False)
    op.create_index('ix_references_id', 'references', ['id'], unique=False)
    op.create_index('ix_references_filter', 'references', ['filter'], unique=False)
    op.create_index('ix_references_created_at', 'references', ['created_at'], unique=False)
    op.drop_index(op.f('ix_refs_validity_start'), table_name='refs')
    op.drop_index(op.f('ix_refs_validity_end'), table_name='refs')
    op.drop_index(op.f('ix_refs_target'), table_name='refs')
    op.drop_index(op.f('ix_refs_section_id'), table_name='refs')
    op.drop_index(op.f('ix_refs_provenance_id'), table_name='refs')
    op.drop_index(op.f('ix_refs_image_id'), table_name='refs')
    op.drop_index(op.f('ix_refs_id'), table_name='refs')
    op.drop_index(op.f('ix_refs_filter'), table_name='refs')
    op.drop_index(op.f('ix_refs_created_at'), table_name='refs')
    op.drop_table('refs')
    # ### end Alembic commands ###
