"""short-filter-names

Revision ID: 1f6d5466990c
Revises: 0df35a4a7925
Create Date: 2024-10-22 15:13:02.378548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6d5466990c'
down_revision = '0df35a4a7925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exposures', sa.Column('_filter', sa.Text(), nullable=True))
    op.drop_index('ix_exposures_filter', table_name='exposures')
    op.create_index(op.f('ix_exposures__filter'), 'exposures', ['_filter'], unique=False)
    op.drop_column('exposures', 'filter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exposures', sa.Column('filter', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_exposures__filter'), table_name='exposures')
    op.create_index('ix_exposures_filter', 'exposures', ['filter'], unique=False)
    op.drop_column('exposures', '_filter')
    # ### end Alembic commands ###
