"""measurements schema

Revision ID: b2129499bfcd
Revises: ef05cbdd10ea
Create Date: 2024-03-13 11:24:47.424264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2129499bfcd'
down_revision = 'ef05cbdd10ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('flux_psf', sa.Float(), nullable=False))
    op.add_column('measurements', sa.Column('flux_psf_err', sa.Float(), nullable=False))
    op.add_column('measurements', sa.Column('flux_apertures', sa.ARRAY(sa.Float()), nullable=False))
    op.add_column('measurements', sa.Column('flux_apertures_err', sa.ARRAY(sa.Float()), nullable=False))
    op.add_column('measurements', sa.Column('aper_radii', sa.ARRAY(sa.Float()), nullable=False))
    op.add_column('measurements', sa.Column('best_aperture', sa.SMALLINT(), nullable=False))
    op.add_column('measurements', sa.Column('background', sa.Float(), nullable=False))
    op.add_column('measurements', sa.Column('background_err', sa.Float(), nullable=False))
    op.add_column('measurements', sa.Column('area_psf', sa.Float(), nullable=False))
    op.add_column('measurements', sa.Column('area_apertures', sa.ARRAY(sa.Float()), nullable=False))
    op.add_column('measurements', sa.Column('offset_x', sa.Float(), nullable=False))
    op.add_column('measurements', sa.Column('offset_y', sa.Float(), nullable=False))
    op.add_column('measurements', sa.Column('width', sa.Float(), nullable=False))
    op.add_column('measurements', sa.Column('elongation', sa.Float(), nullable=False))
    op.add_column('measurements', sa.Column('position_angle', sa.Float(), nullable=False))
    op.add_column('measurements', sa.Column('disqualifier_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_measurements_disqualifier_scores'), 'measurements', ['disqualifier_scores'], unique=False)
    op.create_index('ix_measurements_scores_gin', 'measurements', ['disqualifier_scores'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_measurements_width'), 'measurements', ['width'], unique=False)
    op.create_index('measurements_q3c_ang2ipix_idx', 'measurements', [sa.text('q3c_ang2ipix(ra, "dec")')], unique=False)
    op.drop_constraint('measurements_cutouts_id_fkey', 'measurements', type_='foreignkey')
    op.create_foreign_key('measurements_cutouts_id_fkey', 'measurements', 'cutouts', ['cutouts_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_width'), table_name='measurements')
    op.drop_index('ix_measurements_scores_gin', table_name='measurements', postgresql_using='gin')
    op.drop_index(op.f('ix_measurements_disqualifier_scores'), table_name='measurements')
    op.drop_column('measurements', 'disqualifier_scores')
    op.drop_column('measurements', 'position_angle')
    op.drop_column('measurements', 'elongation')
    op.drop_column('measurements', 'width')
    op.drop_column('measurements', 'offset_y')
    op.drop_column('measurements', 'offset_x')
    op.drop_column('measurements', 'area_apertures')
    op.drop_column('measurements', 'area_psf')
    op.drop_column('measurements', 'background_err')
    op.drop_column('measurements', 'background')
    op.drop_column('measurements', 'best_aperture')
    op.drop_column('measurements', 'aper_radii')
    op.drop_column('measurements', 'flux_apertures_err')
    op.drop_column('measurements', 'flux_apertures')
    op.drop_column('measurements', 'flux_psf_err')
    op.drop_column('measurements', 'flux_psf')
    # ### end Alembic commands ###
