"""user_isadmin

Revision ID: 0b82b234331a
Revises: ea3fabd122d4
Create Date: 2024-11-14 18:00:59.522097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b82b234331a'
down_revision = 'ea3fabd122d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authuser', sa.Column('isadmin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authuser', 'isadmin')
    # ### end Alembic commands ###
