"""deepscore object

Revision ID: 133ca721b561
Revises: 147e28b89b99
Create Date: 2024-09-09 19:29:58.535504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133ca721b561'
down_revision = '147e28b89b99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deepscores',
    sa.Column('_algorithm', sa.SMALLINT(), server_default=sa.text('-1'), nullable=False),
    sa.Column('measurements_id', sa.UUID(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('score', sa.REAL(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['measurements_id'], ['measurements._id'], name='deepscore_measurements_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='deepscore_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_deepscores__id'), 'deepscores', ['_id'], unique=False)
    op.create_index(op.f('ix_deepscores_created_at'), 'deepscores', ['created_at'], unique=False)
    op.create_index(op.f('ix_deepscores_measurements_id'), 'deepscores', ['measurements_id'], unique=False)
    op.create_index(op.f('ix_deepscores_provenance_id'), 'deepscores', ['provenance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deepscores_provenance_id'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores_measurements_id'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores_created_at'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores__id'), table_name='deepscores')
    op.drop_table('deepscores')
    # ### end Alembic commands ###
