"""add report model

Revision ID: 485334f16c23
Revises: 573289f12368
Create Date: 2024-05-15 12:10:56.118620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '485334f16c23'
down_revision = 'ec64a8fd8cf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('exposure_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('num_prev_reports', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('node_id', sa.Text(), nullable=True),
    sa.Column('cluster_id', sa.Text(), nullable=True),
    sa.Column('error_step', sa.Text(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('process_memory', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('process_runtime', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('progress_steps_bitflag', sa.BIGINT(), nullable=False),
    sa.Column('products_exist_bitflag', sa.BIGINT(), nullable=False),
    sa.Column('products_committed_bitflag', sa.BIGINT(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['exposure_id'], ['exposures.id'], name='reports_exposure_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances.id'], name='images_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_exposure_id'), 'reports', ['exposure_id'], unique=False)
    op.create_index(op.f('ix_reports_finish_time'), 'reports', ['finish_time'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_products_committed_bitflag'), 'reports', ['products_committed_bitflag'], unique=False)
    op.create_index(op.f('ix_reports_products_exist_bitflag'), 'reports', ['products_exist_bitflag'], unique=False)
    op.create_index(op.f('ix_reports_progress_steps_bitflag'), 'reports', ['progress_steps_bitflag'], unique=False)
    op.create_index(op.f('ix_reports_provenance_id'), 'reports', ['provenance_id'], unique=False)
    op.create_index(op.f('ix_reports_section_id'), 'reports', ['section_id'], unique=False)
    op.create_index(op.f('ix_reports_start_time'), 'reports', ['start_time'], unique=False)
    op.create_index(op.f('ix_reports_success'), 'reports', ['success'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_success'), table_name='reports')
    op.drop_index(op.f('ix_reports_start_time'), table_name='reports')
    op.drop_index(op.f('ix_reports_section_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_provenance_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_progress_steps_bitflag'), table_name='reports')
    op.drop_index(op.f('ix_reports_products_exist_bitflag'), table_name='reports')
    op.drop_index(op.f('ix_reports_products_committed_bitflag'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_finish_time'), table_name='reports')
    op.drop_index(op.f('ix_reports_exposure_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
