"""conductor_config

Revision ID: 5aeca34b13f7
Revises: 0657d3a80b74
Create Date: 2025-03-07 13:24:03.668191 (but manually bumepd for branch merging)

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5aeca34b13f7'
down_revision = '0657d3a80b74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conductor_config',
    sa.Column('instrument_name', sa.Text(), nullable=True),
    sa.Column('updateargs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('update_timeout', sa.Integer(), nullable=True),
    sa.Column('pause_updates', sa.Boolean(), nullable=True),
    sa.Column('hold_new_exposures', sa.Boolean(), nullable=True),
    sa.Column('configchangetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('throughstep', sa.Text(), nullable=True),
    sa.Column('pickuppartial', sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conductor_config')
    # ### end Alembic commands ###
