"""mod_knownexposures

Revision ID: 0657d3a80b74
Revises: 3f0b9d0c4f76
Create Date: 2025-03-07 02:04:32.441695 (but manually bumped for branch merging)

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0657d3a80b74'
down_revision = '3f0b9d0c4f76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knownexposures', sa.Column('node_id', sa.Text(), nullable=True))
    op.add_column('knownexposures', sa.Column('machine_name', sa.Text(), nullable=True))
    op.add_column('knownexposures', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('knownexposures', sa.Column('release_time', sa.DateTime(), nullable=True))
    op.add_column('knownexposures', sa.Column('provenance_tag', sa.Text(), nullable=True))
    op.add_column('knownexposures', sa.Column('do_not_subtract', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_knownexposures_exposure_id'), 'knownexposures', ['exposure_id'], unique=False)
    op.add_column('pipelineworkers', sa.Column('current_knownexp', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_pipelineworkers_current_knownexp'), 'pipelineworkers', ['current_knownexp'], unique=False)
    op.create_foreign_key('pipelineworker_knownexp_id', 'pipelineworkers', 'knownexposures', ['current_knownexp'], ['_id'])
    op.drop_column('pipelineworkers', 'nexps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelineworkers', sa.Column('nexps', sa.SMALLINT(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_constraint('pipelineworker_knownexp_id', 'pipelineworkers', type_='foreignkey')
    op.drop_index(op.f('ix_pipelineworkers_current_knownexp'), table_name='pipelineworkers')
    op.drop_column('pipelineworkers', 'current_knownexp')
    op.drop_index(op.f('ix_knownexposures_exposure_id'), table_name='knownexposures')
    op.drop_column('knownexposures', 'do_not_subtract')
    op.drop_column('knownexposures', 'provenance_tag')
    op.drop_column('knownexposures', 'release_time')
    op.drop_column('knownexposures', 'start_time')
    op.drop_column('knownexposures', 'machine_name')
    op.drop_column('knownexposures', 'node_id')
    # ### end Alembic commands ###
