"""refactor_image_upstreams

Revision ID: 571f94e49862
Revises: 5a2647d468be
Create Date: 2025-01-08 21:05:15.161862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571f94e49862'
down_revision = '5a2647d468be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_coadd_component',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('coadd_image_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coadd_image_id'], ['images._id'], name='image_coadd_component_coadd_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images._id'], name='image_coadd_component_image_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('image_id', 'coadd_image_id')
    )
    op.drop_table('image_upstreams_association')
    op.add_column('images', sa.Column('coadd_alignment_target', sa.UUID(), nullable=True))
    op.add_column('images', sa.Column('new_image_id', sa.UUID(), nullable=True))
    op.add_column('images', sa.Column('ref_id', sa.UUID(), nullable=True))
    op.drop_index('ix_images_ref_image_id', table_name='images')
    op.create_index(op.f('ix_images_coadd_alignment_target'), 'images', ['coadd_alignment_target'], unique=False)
    op.create_index(op.f('ix_images_new_image_id'), 'images', ['new_image_id'], unique=False)
    op.create_index(op.f('ix_images_ref_id'), 'images', ['ref_id'], unique=False)
    op.drop_constraint('images_ref_image_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key('images_new_image_id_fkey', 'images', 'images', ['new_image_id'], ['_id'], ondelete='RESTRICT')
    op.create_foreign_key('images_ref_id_fkey', 'images', 'refs', ['ref_id'], ['_id'], ondelete='RESTRICT')
    op.create_foreign_key('images_coadd_alignment_target_fkey', 'images', 'images', ['coadd_alignment_target'], ['_id'], ondelete='RESTRICT')
    op.drop_column('images', 'ref_image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('ref_image_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('images_coadd_alignment_target_fkey', 'images', type_='foreignkey')
    op.drop_constraint('images_ref_image_id_fkey', 'images', type_='foreignkey')
    op.drop_constraint('images_new_image_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key('images_ref_image_id_fkey', 'images', 'images', ['ref_image_id'], ['_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_images_ref_id'), table_name='images')
    op.drop_index(op.f('ix_images_new_image_id'), table_name='images')
    op.drop_index(op.f('ix_images_coadd_alignment_target'), table_name='images')
    op.create_index('ix_images_ref_image_id', 'images', ['ref_image_id'], unique=False)
    op.drop_column('images', 'ref_id')
    op.drop_column('images', 'new_image_id')
    op.drop_column('images', 'coadd_alignment_target')
    op.create_table('image_upstreams_association',
    sa.Column('upstream_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('downstream_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['downstream_id'], ['images._id'], name='image_upstreams_association_downstream_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upstream_id'], ['images._id'], name='image_upstreams_association_upstream_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('upstream_id', 'downstream_id', name='image_upstreams_association_pkey')
    )
    op.drop_table('image_coadd_component')
    # ### end Alembic commands ###
