"""fakeset

Revision ID: b863c6368823
Revises: f9a569f36ecf
Create Date: 2025-02-04 16:22:33.812698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b863c6368823'
down_revision = 'f9a569f36ecf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fake_sets',
    sa.Column('zp_id', sa.UUID(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True),
    sa.Column('md5sum', sa.UUID(), nullable=True),
    sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='fake_sets_provenance_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zp_id'], ['zero_points._id'], name='fake_sets_zp_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_fake_sets__id'), 'fake_sets', ['_id'], unique=False)
    op.create_index(op.f('ix_fake_sets_created_at'), 'fake_sets', ['created_at'], unique=False)
    op.create_index(op.f('ix_fake_sets_filepath'), 'fake_sets', ['filepath'], unique=True)
    op.create_index(op.f('ix_fake_sets_provenance_id'), 'fake_sets', ['provenance_id'], unique=False)
    op.create_index(op.f('ix_fake_sets_zp_id'), 'fake_sets', ['zp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fake_sets_zp_id'), table_name='fake_sets')
    op.drop_index(op.f('ix_fake_sets_provenance_id'), table_name='fake_sets')
    op.drop_index(op.f('ix_fake_sets_filepath'), table_name='fake_sets')
    op.drop_index(op.f('ix_fake_sets_created_at'), table_name='fake_sets')
    op.drop_index(op.f('ix_fake_sets__id'), table_name='fake_sets')
    op.drop_table('fake_sets')
    # ### end Alembic commands ###
