"""reference_badness

Revision ID: ba5f61f8d419
Revises: 571f94e49862
Create Date: 2025-01-09 18:44:23.408740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5f61f8d419'
down_revision = '571f94e49862'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refs', sa.Column('_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False))
    op.add_column('refs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('refs', sa.Column('_upstream_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_refs__bitflag'), 'refs', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_refs__upstream_bitflag'), 'refs', ['_upstream_bitflag'], unique=False)
    op.drop_column('refs', 'bad_reason')
    op.drop_column('refs', 'is_bad')
    op.drop_column('refs', 'bad_comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refs', sa.Column('bad_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('refs', sa.Column('is_bad', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('refs', sa.Column('bad_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_refs__upstream_bitflag'), table_name='refs')
    op.drop_index(op.f('ix_refs__bitflag'), table_name='refs')
    op.drop_column('refs', '_upstream_bitflag')
    op.drop_column('refs', 'description')
    op.drop_column('refs', '_bitflag')
    # ### end Alembic commands ###
