"""knownexp_unique

Revision ID: eec1bc160d1f
Revises: 5aeca34b13f7
Create Date: 2025-03-07 22:58:04.190788 (but manually bumped for branch merging)

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec1bc160d1f'
down_revision = '5aeca34b13f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_ke_unique_inst_ident', 'knownexposures', ['instrument', 'identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_ke_unique_inst_ident', 'knownexposures', type_='unique')
    # ### end Alembic commands ###
