"""fakeanalysis

Revision ID: e447efae5462
Revises: b863c6368823
Create Date: 2025-02-10 21:18:17.572515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e447efae5462'
down_revision = 'b863c6368823'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fake_analysis',
    sa.Column('fakeset_id', sa.UUID(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True),
    sa.Column('md5sum', sa.UUID(), nullable=True),
    sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['fakeset_id'], ['fake_sets._id'], name='fake_analysis_fake_sets_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='fake_analysis_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_fake_analysis__id'), 'fake_analysis', ['_id'], unique=False)
    op.create_index(op.f('ix_fake_analysis_created_at'), 'fake_analysis', ['created_at'], unique=False)
    op.create_index(op.f('ix_fake_analysis_fakeset_id'), 'fake_analysis', ['fakeset_id'], unique=False)
    op.create_index(op.f('ix_fake_analysis_filepath'), 'fake_analysis', ['filepath'], unique=True)
    op.create_index(op.f('ix_fake_analysis_provenance_id'), 'fake_analysis', ['provenance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fake_analysis_provenance_id'), table_name='fake_analysis')
    op.drop_index(op.f('ix_fake_analysis_filepath'), table_name='fake_analysis')
    op.drop_index(op.f('ix_fake_analysis_fakeset_id'), table_name='fake_analysis')
    op.drop_index(op.f('ix_fake_analysis_created_at'), table_name='fake_analysis')
    op.drop_index(op.f('ix_fake_analysis__id'), table_name='fake_analysis')
    op.drop_table('fake_analysis')
    # ### end Alembic commands ###
