"""test2

Revision ID: ff8f1c5af08c
Revises: 91610b539a79
Create Date: 2025-03-10 16:16:20.305700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8f1c5af08c'
down_revision = '91610b539a79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provenances', sa.Column('code_version_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_provenances_code_version_id'), 'provenances', ['code_version_id'], unique=False)
    op.create_foreign_key('provenances_code_version_id_fkey', 'provenances', 'code_versions', ['code_version_id'], ['_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('provenances_code_version_id_fkey', 'provenances', type_='foreignkey')
    op.drop_index(op.f('ix_provenances_code_version_id'), table_name='provenances')
    op.drop_column('provenances', 'code_version_id')
    # ### end Alembic commands ###
