"""background_with_extraction

Revision ID: 13c3aa45bd4d
Revises: 2146f40eb298
Create Date: 2025-03-12 18:42:57.846000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c3aa45bd4d'
down_revision = '2146f40eb298'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_background_source_list_provenance_ud', 'backgrounds', type_='unique')
    op.drop_index('ix_backgrounds_provenance_id', table_name='backgrounds')
    op.create_unique_constraint('_background_source_list_ud', 'backgrounds', ['sources_id'])
    op.drop_constraint('background_provenance_id_fkey', 'backgrounds', type_='foreignkey')
    op.drop_column('backgrounds', 'provenance_id')
    op.drop_constraint('_zp_wcs_bg_provenance_uc', 'zero_points', type_='unique')
    op.drop_index('ix_zero_points_background_id', table_name='zero_points')
    op.create_unique_constraint('_zp_wcs_provenance_uc', 'zero_points', ['wcs_id', 'provenance_id'])
    op.drop_constraint('zp_background_id_fkey', 'zero_points', type_='foreignkey')
    op.drop_column('zero_points', 'background_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zero_points', sa.Column('background_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('zp_background_id_fkey', 'zero_points', 'backgrounds', ['background_id'], ['_id'], ondelete='CASCADE')
    op.drop_constraint('_zp_wcs_provenance_uc', 'zero_points', type_='unique')
    op.create_index('ix_zero_points_background_id', 'zero_points', ['background_id'], unique=False)
    op.create_unique_constraint('_zp_wcs_bg_provenance_uc', 'zero_points', ['wcs_id', 'background_id', 'provenance_id'])
    op.add_column('backgrounds', sa.Column('provenance_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('background_provenance_id_fkey', 'backgrounds', 'provenances', ['provenance_id'], ['_id'], ondelete='CASCADE')
    op.drop_constraint('_background_source_list_ud', 'backgrounds', type_='unique')
    op.create_index('ix_backgrounds_provenance_id', 'backgrounds', ['provenance_id'], unique=False)
    op.create_unique_constraint('_background_source_list_provenance_ud', 'backgrounds', ['sources_id', 'provenance_id'])
    # ### end Alembic commands ###
