"""update_reports

Revision ID: 3f0b9d0c4f76
Revises: 13c3aa45bd4d
Create Date: 2025-02-28 15:51:30.856254 (but manually bumped for branch merging)

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f0b9d0c4f76'
down_revision = '13c3aa45bd4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('image_id', sa.UUID(), nullable=True))
    op.add_column('reports', sa.Column('process_provid', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('reports', 'exposure_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reports', 'section_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index('ix_reports_products_committed_bitflag', table_name='reports')
    op.drop_index('ix_reports_products_exist_bitflag', table_name='reports')
    op.drop_index('ix_reports_progress_steps_bitflag', table_name='reports')
    op.drop_index('ix_reports_provenance_id', table_name='reports')
    op.drop_index('ix_reports_success', table_name='reports')
    op.create_index(op.f('ix_reports_image_id'), 'reports', ['image_id'], unique=False)
    op.drop_constraint('reports_provenance_id_fkey', 'reports', type_='foreignkey')
    op.drop_column('reports', 'provenance_id')
    op.drop_column('reports', 'worker_id')
    op.drop_column('reports', 'num_prev_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('num_prev_reports', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('worker_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('provenance_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('reports_provenance_id_fkey', 'reports', 'provenances', ['provenance_id'], ['_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reports_image_id'), table_name='reports')
    op.create_index('ix_reports_success', 'reports', ['success'], unique=False)
    op.create_index('ix_reports_provenance_id', 'reports', ['provenance_id'], unique=False)
    op.create_index('ix_reports_progress_steps_bitflag', 'reports', ['progress_steps_bitflag'], unique=False)
    op.create_index('ix_reports_products_exist_bitflag', 'reports', ['products_exist_bitflag'], unique=False)
    op.create_index('ix_reports_products_committed_bitflag', 'reports', ['products_committed_bitflag'], unique=False)
    op.alter_column('reports', 'section_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('reports', 'exposure_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('reports', 'process_provid')
    op.drop_column('reports', 'image_id')
    # ### end Alembic commands ###
