"""test1

Revision ID: 91610b539a79
Revises: 13c3aa45bd4d
Create Date: 2025-03-10 16:13:32.865783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91610b539a79'
down_revision = '13c3aa45bd4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('code_hashes_code_version_id_fkey', 'code_hashes', type_='foreignkey')

    op.drop_index('ix_provenances_code_version_id', table_name='provenances')
    op.drop_constraint('provenances_code_version_id_fkey', 'provenances', type_='foreignkey')
    op.drop_column('provenances', 'code_version_id')

    op.add_column('code_versions', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('code_versions', sa.Column('process', sa.String(), nullable=False))
    op.alter_column('code_versions', '_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='_id::uuid')
    op.create_index(op.f('ix_code_versions__id'), 'code_versions', ['_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_code_versions__id'), table_name='code_versions')
    op.alter_column('code_versions', '_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('code_versions', 'process')
    op.drop_column('code_versions', 'version')

    op.add_column('provenances', sa.Column('code_version_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('provenances_code_version_id_fkey', 'provenances', 'code_versions', ['code_version_id'], ['_id'], ondelete='CASCADE')
    op.create_index('ix_provenances_code_version_id', 'provenances', ['code_version_id'], unique=False)

    op.create_foreign_key('code_hashes_code_version_id_fkey', 'code_hashes', 'code_versions', ['code_version_id'], ['_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
