"""object_naming

Revision ID: 2146f40eb298
Revises: 8a9305b0daca
Create Date: 2025-03-06 02:39:09.962455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2146f40eb298'
down_revision = '8a9305b0daca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_name_max_used',
    sa.Column('year', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('maxnum', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    op.drop_column('objects', 'is_fake')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('is_fake', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_table('object_name_max_used')
    # ### end Alembic commands ###
