"""authgroup

Revision ID: 8a9305b0daca
Revises: e0716e84774f
Create Date: 2025-02-27 17:26:46.729202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9305b0daca'
down_revision = 'e0716e84774f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authgroup',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authgroup_created_at'), 'authgroup', ['created_at'], unique=False)
    op.create_index(op.f('ix_authgroup_name'), 'authgroup', ['name'], unique=True)
    op.create_table('auth_user_group',
    sa.Column('userid', sa.UUID(), nullable=False),
    sa.Column('groupid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['groupid'], ['authgroup.id'], name='auth_user_group_group_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userid'], ['authuser.id'], name='auth_user_group_user_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userid', 'groupid')
    )
    op.create_index(op.f('ix_auth_user_group_groupid'), 'auth_user_group', ['groupid'], unique=False)
    op.create_index(op.f('ix_auth_user_group_userid'), 'auth_user_group', ['userid'], unique=False)
    op.drop_column('authuser', 'isadmin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authuser', sa.Column('isadmin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_auth_user_group_userid'), table_name='auth_user_group')
    op.drop_index(op.f('ix_auth_user_group_groupid'), table_name='auth_user_group')
    op.drop_table('auth_user_group')
    op.drop_index(op.f('ix_authgroup_name'), table_name='authgroup')
    op.drop_index(op.f('ix_authgroup_created_at'), table_name='authgroup')
    op.drop_table('authgroup')
    # ### end Alembic commands ###
