"""objectposition

Revision ID: 5ef7f7c09451
Revises: eec1bc160d1f
Create Date: 2025-05-15 14:22:36.754005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef7f7c09451'
down_revision = 'eec1bc160d1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_positions',
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('dra', sa.REAL(), nullable=False),
    sa.Column('ddec', sa.REAL(), nullable=False),
    sa.Column('ra_dec_cov', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('ra', sa.Double(), nullable=False),
    sa.Column('dec', sa.Double(), nullable=False),
    sa.Column('gallat', sa.Double(), nullable=True),
    sa.Column('gallon', sa.Double(), nullable=True),
    sa.Column('ecllat', sa.Double(), nullable=True),
    sa.Column('ecllon', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects._id'], name='object_position_object_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='object_position_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('object_id', 'provenance_id', name='object_position_obj_prov_unique')
    )
    op.create_index(op.f('ix_object_positions__id'), 'object_positions', ['_id'], unique=False)
    op.create_index(op.f('ix_object_positions_created_at'), 'object_positions', ['created_at'], unique=False)
    op.create_index(op.f('ix_object_positions_ecllat'), 'object_positions', ['ecllat'], unique=False)
    op.create_index(op.f('ix_object_positions_gallat'), 'object_positions', ['gallat'], unique=False)
    op.create_index(op.f('ix_object_positions_object_id'), 'object_positions', ['object_id'], unique=False)
    op.create_index(op.f('ix_object_positions_provenance_id'), 'object_positions', ['provenance_id'], unique=False)
    op.create_index('object_positions_q3c_ang2ipix_idx', 'object_positions', [sa.text('q3c_ang2ipix(ra, dec)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('object_positions_q3c_ang2ipix_idx', table_name='object_positions')
    op.drop_index(op.f('ix_object_positions_provenance_id'), table_name='object_positions')
    op.drop_index(op.f('ix_object_positions_object_id'), table_name='object_positions')
    op.drop_index(op.f('ix_object_positions_gallat'), table_name='object_positions')
    op.drop_index(op.f('ix_object_positions_ecllat'), table_name='object_positions')
    op.drop_index(op.f('ix_object_positions_created_at'), table_name='object_positions')
    op.drop_index(op.f('ix_object_positions__id'), table_name='object_positions')
    op.drop_table('object_positions')
    # ### end Alembic commands ###
