"""codeversion rework pt3

Revision ID: ddb3f80c9bfb
Revises: ff8f1c5af08c
Create Date: 2025-05-15 15:59:10.278792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddb3f80c9bfb'
down_revision = 'ff8f1c5af08c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_code_hashes_code_version_id', table_name='code_hashes')
    op.drop_index('ix_code_hashes_created_at', table_name='code_hashes')
    op.drop_table('code_hashes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_hashes',
    sa.Column('_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code_version_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('_id', name='code_hashes_pkey')
    )
    op.create_index('ix_code_hashes_created_at', 'code_hashes', ['created_at'], unique=False)
    op.create_index('ix_code_hashes_code_version_id', 'code_hashes', ['code_version_id'], unique=False)
    # ### end Alembic commands ###
