"""reboot

Revision ID: f9a569f36ecf
Revises: 
Create Date: 2025-01-29 20:32:31.707488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9a569f36ecf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authuser',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('displayname', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('pubkey', sa.Text(), nullable=True),
    sa.Column('privkey', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('isadmin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authuser_created_at'), 'authuser', ['created_at'], unique=False)
    op.create_index(op.f('ix_authuser_email'), 'authuser', ['email'], unique=False)
    op.create_index(op.f('ix_authuser_username'), 'authuser', ['username'], unique=True)
    op.create_table('calibfile_downloadlock',
    sa.Column('_type', sa.SMALLINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('_calibrator_set', sa.SMALLINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('_flat_type', sa.SMALLINT(), nullable=True),
    sa.Column('instrument', sa.Text(), nullable=False),
    sa.Column('sensor_section', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_type', '_calibrator_set', '_flat_type', 'instrument', 'sensor_section', name='calibfile_downloadlock_unique', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_calibfile_downloadlock__id'), 'calibfile_downloadlock', ['_id'], unique=False)
    op.create_index(op.f('ix_calibfile_downloadlock_created_at'), 'calibfile_downloadlock', ['created_at'], unique=False)
    op.create_table('catalog_excerpts',
    sa.Column('_format', sa.SMALLINT(), server_default=sa.text('16'), nullable=False),
    sa.Column('_origin', sa.SMALLINT(), nullable=False),
    sa.Column('num_items', sa.Integer(), nullable=False),
    sa.Column('minmag', sa.REAL(), nullable=True),
    sa.Column('maxmag', sa.REAL(), nullable=True),
    sa.Column('filters', postgresql.ARRAY(sa.Text(), zero_indexes=True), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True),
    sa.Column('md5sum', sa.UUID(), nullable=True),
    sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('ra', sa.Double(), nullable=False),
    sa.Column('dec', sa.Double(), nullable=False),
    sa.Column('gallat', sa.Double(), nullable=True),
    sa.Column('gallon', sa.Double(), nullable=True),
    sa.Column('ecllat', sa.Double(), nullable=True),
    sa.Column('ecllon', sa.Double(), nullable=True),
    sa.Column('ra_corner_00', sa.REAL(), nullable=False),
    sa.Column('ra_corner_01', sa.REAL(), nullable=False),
    sa.Column('ra_corner_10', sa.REAL(), nullable=False),
    sa.Column('ra_corner_11', sa.REAL(), nullable=False),
    sa.Column('dec_corner_00', sa.REAL(), nullable=False),
    sa.Column('dec_corner_01', sa.REAL(), nullable=False),
    sa.Column('dec_corner_10', sa.REAL(), nullable=False),
    sa.Column('dec_corner_11', sa.REAL(), nullable=False),
    sa.Column('minra', sa.REAL(), nullable=False),
    sa.Column('maxra', sa.REAL(), nullable=False),
    sa.Column('mindec', sa.REAL(), nullable=False),
    sa.Column('maxdec', sa.REAL(), nullable=False),
    sa.CheckConstraint('NOT(md5sum IS NULL AND (md5sum_components IS NULL OR array_position(md5sum_components, NULL) IS NOT NULL))', name='catalog_excerpts_md5sum_check'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index('catalog_excerpts_q3c_ang2ipix_idx', 'catalog_excerpts', [sa.text('q3c_ang2ipix(ra, dec)')], unique=False)
    op.create_index(op.f('ix_catalog_excerpts__id'), 'catalog_excerpts', ['_id'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts__origin'), 'catalog_excerpts', ['_origin'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_created_at'), 'catalog_excerpts', ['created_at'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_dec_corner_00'), 'catalog_excerpts', ['dec_corner_00'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_dec_corner_01'), 'catalog_excerpts', ['dec_corner_01'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_dec_corner_10'), 'catalog_excerpts', ['dec_corner_10'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_dec_corner_11'), 'catalog_excerpts', ['dec_corner_11'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_ecllat'), 'catalog_excerpts', ['ecllat'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_filepath'), 'catalog_excerpts', ['filepath'], unique=True)
    op.create_index(op.f('ix_catalog_excerpts_gallat'), 'catalog_excerpts', ['gallat'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_maxdec'), 'catalog_excerpts', ['maxdec'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_maxmag'), 'catalog_excerpts', ['maxmag'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_maxra'), 'catalog_excerpts', ['maxra'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_mindec'), 'catalog_excerpts', ['mindec'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_minmag'), 'catalog_excerpts', ['minmag'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_minra'), 'catalog_excerpts', ['minra'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_num_items'), 'catalog_excerpts', ['num_items'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_ra_corner_00'), 'catalog_excerpts', ['ra_corner_00'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_ra_corner_01'), 'catalog_excerpts', ['ra_corner_01'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_ra_corner_10'), 'catalog_excerpts', ['ra_corner_10'], unique=False)
    op.create_index(op.f('ix_catalog_excerpts_ra_corner_11'), 'catalog_excerpts', ['ra_corner_11'], unique=False)
    op.create_table('code_versions',
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_code_versions_created_at'), 'code_versions', ['created_at'], unique=False)
    op.create_table('gaiadr3_downloadlock',
    sa.Column('minra', sa.REAL(), nullable=False),
    sa.Column('maxra', sa.REAL(), nullable=False),
    sa.Column('mindec', sa.REAL(), nullable=False),
    sa.Column('maxdec', sa.REAL(), nullable=False),
    sa.Column('minmag', sa.REAL(), nullable=True),
    sa.Column('maxmag', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_gaiadr3_downloadlock__id'), 'gaiadr3_downloadlock', ['_id'], unique=False)
    op.create_index(op.f('ix_gaiadr3_downloadlock_created_at'), 'gaiadr3_downloadlock', ['created_at'], unique=False)
    op.create_table('objects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_test', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_fake', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_bad', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('ra', sa.Double(), nullable=False),
    sa.Column('dec', sa.Double(), nullable=False),
    sa.Column('gallat', sa.Double(), nullable=True),
    sa.Column('gallon', sa.Double(), nullable=True),
    sa.Column('ecllat', sa.Double(), nullable=True),
    sa.Column('ecllon', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_objects__id'), 'objects', ['_id'], unique=False)
    op.create_index(op.f('ix_objects_created_at'), 'objects', ['created_at'], unique=False)
    op.create_index(op.f('ix_objects_ecllat'), 'objects', ['ecllat'], unique=False)
    op.create_index(op.f('ix_objects_gallat'), 'objects', ['gallat'], unique=False)
    op.create_index(op.f('ix_objects_is_bad'), 'objects', ['is_bad'], unique=False)
    op.create_index(op.f('ix_objects_name'), 'objects', ['name'], unique=True)
    op.create_index('objects_q3c_ang2ipix_idx', 'objects', [sa.text('q3c_ang2ipix(ra, dec)')], unique=False)
    op.create_table('pipelineworkers',
    sa.Column('cluster_id', sa.Text(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=True),
    sa.Column('nexps', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('lastheartbeat', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_pipelineworkers__id'), 'pipelineworkers', ['_id'], unique=False)
    op.create_index(op.f('ix_pipelineworkers_created_at'), 'pipelineworkers', ['created_at'], unique=False)
    op.create_table('sensor_sections',
    sa.Column('instrument', sa.Text(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('validity_start', sa.DateTime(), nullable=True),
    sa.Column('validity_end', sa.DateTime(), nullable=True),
    sa.Column('size_x', sa.Integer(), nullable=True),
    sa.Column('size_y', sa.Integer(), nullable=True),
    sa.Column('offset_x', sa.Integer(), nullable=True),
    sa.Column('offset_y', sa.Integer(), nullable=True),
    sa.Column('filter_array_index', sa.Integer(), nullable=True),
    sa.Column('read_noise', sa.REAL(), nullable=True),
    sa.Column('dark_current', sa.REAL(), nullable=True),
    sa.Column('gain', sa.REAL(), nullable=True),
    sa.Column('saturation_limit', sa.REAL(), nullable=True),
    sa.Column('non_linearity_limit', sa.REAL(), nullable=True),
    sa.Column('defective', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_sensor_sections__id'), 'sensor_sections', ['_id'], unique=False)
    op.create_index(op.f('ix_sensor_sections_created_at'), 'sensor_sections', ['created_at'], unique=False)
    op.create_index(op.f('ix_sensor_sections_defective'), 'sensor_sections', ['defective'], unique=False)
    op.create_index(op.f('ix_sensor_sections_identifier'), 'sensor_sections', ['identifier'], unique=False)
    op.create_index(op.f('ix_sensor_sections_instrument'), 'sensor_sections', ['instrument'], unique=False)
    op.create_index(op.f('ix_sensor_sections_validity_end'), 'sensor_sections', ['validity_end'], unique=False)
    op.create_index(op.f('ix_sensor_sections_validity_start'), 'sensor_sections', ['validity_start'], unique=False)
    op.create_table('code_hashes',
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('code_version_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code_version_id'], ['code_versions._id'], name='code_hashes_code_version_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_code_hashes_code_version_id'), 'code_hashes', ['code_version_id'], unique=False)
    op.create_index(op.f('ix_code_hashes_created_at'), 'code_hashes', ['created_at'], unique=False)
    op.create_table('passwordlink',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userid', sa.UUID(), nullable=True),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['authuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordlink_created_at'), 'passwordlink', ['created_at'], unique=False)
    op.create_index(op.f('ix_passwordlink_userid'), 'passwordlink', ['userid'], unique=False)
    op.create_table('provenances',
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('process', sa.String(), nullable=False),
    sa.Column('code_version_id', sa.String(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_bad', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('bad_comment', sa.String(), nullable=True),
    sa.Column('is_outdated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('replaced_by', sa.String(), nullable=True),
    sa.Column('is_testing', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code_version_id'], ['code_versions._id'], name='provenances_code_version_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaced_by'], ['provenances._id'], name='provenances_replaced_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_provenances_code_version_id'), 'provenances', ['code_version_id'], unique=False)
    op.create_index(op.f('ix_provenances_created_at'), 'provenances', ['created_at'], unique=False)
    op.create_index(op.f('ix_provenances_process'), 'provenances', ['process'], unique=False)
    op.create_index(op.f('ix_provenances_replaced_by'), 'provenances', ['replaced_by'], unique=False)
    op.create_table('data_files',
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True),
    sa.Column('md5sum', sa.UUID(), nullable=True),
    sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.CheckConstraint('NOT(md5sum IS NULL AND (md5sum_components IS NULL OR array_position(md5sum_components, NULL) IS NOT NULL))', name='data_files_md5sum_check'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='data_files_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_data_files__id'), 'data_files', ['_id'], unique=False)
    op.create_index(op.f('ix_data_files_created_at'), 'data_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_files_filepath'), 'data_files', ['filepath'], unique=True)
    op.create_index(op.f('ix_data_files_provenance_id'), 'data_files', ['provenance_id'], unique=False)
    op.create_table('exposures',
    sa.Column('_type', sa.SMALLINT(), server_default=sa.text('1'), nullable=False),
    sa.Column('_format', sa.SMALLINT(), server_default=sa.text('1'), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('mjd', sa.Double(), nullable=False),
    sa.Column('exp_time', sa.REAL(), nullable=False),
    sa.Column('_filter', sa.Text(), nullable=True),
    sa.Column('airmass', sa.REAL(), nullable=True),
    sa.Column('filter_array', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True),
    sa.Column('instrument', sa.Text(), nullable=False),
    sa.Column('project', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('preproc_bitflag', sa.SMALLINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('origin_identifier', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True),
    sa.Column('md5sum', sa.UUID(), nullable=True),
    sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('ra', sa.Double(), nullable=False),
    sa.Column('dec', sa.Double(), nullable=False),
    sa.Column('gallat', sa.Double(), nullable=True),
    sa.Column('gallon', sa.Double(), nullable=True),
    sa.Column('ecllat', sa.Double(), nullable=True),
    sa.Column('ecllon', sa.Double(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint('NOT(_filter IS NULL AND filter_array IS NULL)', name='exposures_filter_or_array_check'),
    sa.CheckConstraint('NOT(md5sum IS NULL AND (md5sum_components IS NULL OR array_position(md5sum_components, NULL) IS NOT NULL))', name='exposures_md5sum_check'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index('exposures_q3c_ang2ipix_idx', 'exposures', [sa.text('q3c_ang2ipix(ra, dec)')], unique=False)
    op.create_index(op.f('ix_exposures__bitflag'), 'exposures', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_exposures__filter'), 'exposures', ['_filter'], unique=False)
    op.create_index(op.f('ix_exposures__id'), 'exposures', ['_id'], unique=False)
    op.create_index(op.f('ix_exposures__type'), 'exposures', ['_type'], unique=False)
    op.create_index(op.f('ix_exposures_airmass'), 'exposures', ['airmass'], unique=False)
    op.create_index(op.f('ix_exposures_created_at'), 'exposures', ['created_at'], unique=False)
    op.create_index(op.f('ix_exposures_ecllat'), 'exposures', ['ecllat'], unique=False)
    op.create_index(op.f('ix_exposures_exp_time'), 'exposures', ['exp_time'], unique=False)
    op.create_index(op.f('ix_exposures_filepath'), 'exposures', ['filepath'], unique=True)
    op.create_index(op.f('ix_exposures_filter_array'), 'exposures', ['filter_array'], unique=False)
    op.create_index(op.f('ix_exposures_gallat'), 'exposures', ['gallat'], unique=False)
    op.create_index(op.f('ix_exposures_instrument'), 'exposures', ['instrument'], unique=False)
    op.create_index(op.f('ix_exposures_mjd'), 'exposures', ['mjd'], unique=False)
    op.create_index(op.f('ix_exposures_origin_identifier'), 'exposures', ['origin_identifier'], unique=False)
    op.create_index(op.f('ix_exposures_project'), 'exposures', ['project'], unique=False)
    op.create_index(op.f('ix_exposures_provenance_id'), 'exposures', ['provenance_id'], unique=False)
    op.create_index(op.f('ix_exposures_target'), 'exposures', ['target'], unique=False)
    op.create_table('provenance_tags',
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='provenance_tags_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('tag', 'provenance_id', name='_provenancetag_prov_tag_uc')
    )
    op.create_index(op.f('ix_provenance_tags__id'), 'provenance_tags', ['_id'], unique=False)
    op.create_index(op.f('ix_provenance_tags_created_at'), 'provenance_tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_provenance_tags_provenance_id'), 'provenance_tags', ['provenance_id'], unique=False)
    op.create_index(op.f('ix_provenance_tags_tag'), 'provenance_tags', ['tag'], unique=False)
    op.create_table('provenance_upstreams',
    sa.Column('upstream_id', sa.String(), nullable=False),
    sa.Column('downstream_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['downstream_id'], ['provenances._id'], name='provenance_upstreams_downstream_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upstream_id'], ['provenances._id'], name='provenance_upstreams_upstream_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upstream_id', 'downstream_id')
    )
    op.create_table('refsets',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='refset_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_refsets__id'), 'refsets', ['_id'], unique=False)
    op.create_index(op.f('ix_refsets_created_at'), 'refsets', ['created_at'], unique=False)
    op.create_index(op.f('ix_refsets_name'), 'refsets', ['name'], unique=True)
    op.create_index(op.f('ix_refsets_provenance_id'), 'refsets', ['provenance_id'], unique=False)
    op.create_table('images',
    sa.Column('_format', sa.SMALLINT(), server_default=sa.text('1'), nullable=False),
    sa.Column('exposure_id', sa.UUID(), nullable=True),
    sa.Column('is_coadd', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('coadd_alignment_target', sa.UUID(), nullable=True),
    sa.Column('is_sub', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('_type', sa.SMALLINT(), server_default=sa.text('1'), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('mjd', sa.Double(), nullable=False),
    sa.Column('end_mjd', sa.Double(), nullable=False),
    sa.Column('exp_time', sa.REAL(), nullable=False),
    sa.Column('instrument', sa.Text(), nullable=False),
    sa.Column('telescope', sa.Text(), nullable=False),
    sa.Column('filter', sa.Text(), nullable=True),
    sa.Column('section_id', sa.Text(), nullable=True),
    sa.Column('project', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('preproc_bitflag', sa.SMALLINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('astro_cal_done', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('sky_sub_done', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('airmass', sa.REAL(), nullable=True),
    sa.Column('fwhm_estimate', sa.REAL(), nullable=True),
    sa.Column('zero_point_estimate', sa.REAL(), nullable=True),
    sa.Column('lim_mag_estimate', sa.REAL(), nullable=True),
    sa.Column('bkg_mean_estimate', sa.REAL(), nullable=True),
    sa.Column('bkg_rms_estimate', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True),
    sa.Column('md5sum', sa.UUID(), nullable=True),
    sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('ra', sa.Double(), nullable=False),
    sa.Column('dec', sa.Double(), nullable=False),
    sa.Column('gallat', sa.Double(), nullable=True),
    sa.Column('gallon', sa.Double(), nullable=True),
    sa.Column('ecllat', sa.Double(), nullable=True),
    sa.Column('ecllon', sa.Double(), nullable=True),
    sa.Column('ra_corner_00', sa.REAL(), nullable=False),
    sa.Column('ra_corner_01', sa.REAL(), nullable=False),
    sa.Column('ra_corner_10', sa.REAL(), nullable=False),
    sa.Column('ra_corner_11', sa.REAL(), nullable=False),
    sa.Column('dec_corner_00', sa.REAL(), nullable=False),
    sa.Column('dec_corner_01', sa.REAL(), nullable=False),
    sa.Column('dec_corner_10', sa.REAL(), nullable=False),
    sa.Column('dec_corner_11', sa.REAL(), nullable=False),
    sa.Column('minra', sa.REAL(), nullable=False),
    sa.Column('maxra', sa.REAL(), nullable=False),
    sa.Column('mindec', sa.REAL(), nullable=False),
    sa.Column('maxdec', sa.REAL(), nullable=False),
    sa.Column('_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_upstream_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('NOT(md5sum IS NULL AND (md5sum_components IS NULL OR array_position(md5sum_components, NULL) IS NOT NULL))', name='images_md5sum_check'),
    sa.ForeignKeyConstraint(['coadd_alignment_target'], ['images._id'], name='images_coadd_alignment_target_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exposure_id'], ['exposures._id'], name='images_exposure_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='images_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index('images_q3c_ang2ipix_idx', 'images', [sa.text('q3c_ang2ipix(ra, dec)')], unique=False)
    op.create_index(op.f('ix_images__bitflag'), 'images', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_images__id'), 'images', ['_id'], unique=False)
    op.create_index(op.f('ix_images__type'), 'images', ['_type'], unique=False)
    op.create_index(op.f('ix_images__upstream_bitflag'), 'images', ['_upstream_bitflag'], unique=False)
    op.create_index(op.f('ix_images_airmass'), 'images', ['airmass'], unique=False)
    op.create_index(op.f('ix_images_bkg_mean_estimate'), 'images', ['bkg_mean_estimate'], unique=False)
    op.create_index(op.f('ix_images_bkg_rms_estimate'), 'images', ['bkg_rms_estimate'], unique=False)
    op.create_index(op.f('ix_images_coadd_alignment_target'), 'images', ['coadd_alignment_target'], unique=False)
    op.create_index(op.f('ix_images_created_at'), 'images', ['created_at'], unique=False)
    op.create_index(op.f('ix_images_dec_corner_00'), 'images', ['dec_corner_00'], unique=False)
    op.create_index(op.f('ix_images_dec_corner_01'), 'images', ['dec_corner_01'], unique=False)
    op.create_index(op.f('ix_images_dec_corner_10'), 'images', ['dec_corner_10'], unique=False)
    op.create_index(op.f('ix_images_dec_corner_11'), 'images', ['dec_corner_11'], unique=False)
    op.create_index(op.f('ix_images_ecllat'), 'images', ['ecllat'], unique=False)
    op.create_index(op.f('ix_images_end_mjd'), 'images', ['end_mjd'], unique=False)
    op.create_index(op.f('ix_images_exp_time'), 'images', ['exp_time'], unique=False)
    op.create_index(op.f('ix_images_exposure_id'), 'images', ['exposure_id'], unique=False)
    op.create_index(op.f('ix_images_filepath'), 'images', ['filepath'], unique=True)
    op.create_index(op.f('ix_images_filter'), 'images', ['filter'], unique=False)
    op.create_index(op.f('ix_images_fwhm_estimate'), 'images', ['fwhm_estimate'], unique=False)
    op.create_index(op.f('ix_images_gallat'), 'images', ['gallat'], unique=False)
    op.create_index(op.f('ix_images_instrument'), 'images', ['instrument'], unique=False)
    op.create_index(op.f('ix_images_is_coadd'), 'images', ['is_coadd'], unique=False)
    op.create_index(op.f('ix_images_is_sub'), 'images', ['is_sub'], unique=False)
    op.create_index(op.f('ix_images_lim_mag_estimate'), 'images', ['lim_mag_estimate'], unique=False)
    op.create_index(op.f('ix_images_maxdec'), 'images', ['maxdec'], unique=False)
    op.create_index(op.f('ix_images_maxra'), 'images', ['maxra'], unique=False)
    op.create_index(op.f('ix_images_mindec'), 'images', ['mindec'], unique=False)
    op.create_index(op.f('ix_images_minra'), 'images', ['minra'], unique=False)
    op.create_index(op.f('ix_images_mjd'), 'images', ['mjd'], unique=False)
    op.create_index(op.f('ix_images_project'), 'images', ['project'], unique=False)
    op.create_index(op.f('ix_images_provenance_id'), 'images', ['provenance_id'], unique=False)
    op.create_index(op.f('ix_images_ra_corner_00'), 'images', ['ra_corner_00'], unique=False)
    op.create_index(op.f('ix_images_ra_corner_01'), 'images', ['ra_corner_01'], unique=False)
    op.create_index(op.f('ix_images_ra_corner_10'), 'images', ['ra_corner_10'], unique=False)
    op.create_index(op.f('ix_images_ra_corner_11'), 'images', ['ra_corner_11'], unique=False)
    op.create_index(op.f('ix_images_section_id'), 'images', ['section_id'], unique=False)
    op.create_index(op.f('ix_images_target'), 'images', ['target'], unique=False)
    op.create_index(op.f('ix_images_telescope'), 'images', ['telescope'], unique=False)
    op.create_index(op.f('ix_images_zero_point_estimate'), 'images', ['zero_point_estimate'], unique=False)
    op.create_table('knownexposures',
    sa.Column('instrument', sa.Text(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hold', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('exposure_id', sa.UUID(), nullable=True),
    sa.Column('mjd', sa.Double(), nullable=True),
    sa.Column('exp_time', sa.REAL(), nullable=True),
    sa.Column('filter', sa.Text(), nullable=True),
    sa.Column('project', sa.Text(), nullable=True),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('cluster_id', sa.Text(), nullable=True),
    sa.Column('claim_time', sa.DateTime(), nullable=True),
    sa.Column('ra', sa.Double(), nullable=True),
    sa.Column('dec', sa.Double(), nullable=True),
    sa.Column('gallat', sa.Double(), nullable=True),
    sa.Column('gallon', sa.Double(), nullable=True),
    sa.Column('ecllat', sa.Double(), nullable=True),
    sa.Column('ecllon', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exposure_id'], ['exposures._id'], name='knownexposure_exposure_id_fkey'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_knownexposures__id'), 'knownexposures', ['_id'], unique=False)
    op.create_index(op.f('ix_knownexposures_created_at'), 'knownexposures', ['created_at'], unique=False)
    op.create_index(op.f('ix_knownexposures_ecllat'), 'knownexposures', ['ecllat'], unique=False)
    op.create_index(op.f('ix_knownexposures_gallat'), 'knownexposures', ['gallat'], unique=False)
    op.create_index(op.f('ix_knownexposures_identifier'), 'knownexposures', ['identifier'], unique=False)
    op.create_index(op.f('ix_knownexposures_instrument'), 'knownexposures', ['instrument'], unique=False)
    op.create_index(op.f('ix_knownexposures_mjd'), 'knownexposures', ['mjd'], unique=False)
    op.create_index('knownexposures_q3c_ang2ipix_idx', 'knownexposures', [sa.text('q3c_ang2ipix(ra, dec)')], unique=False)
    op.create_table('reports',
    sa.Column('exposure_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('num_prev_reports', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('node_id', sa.Text(), nullable=True),
    sa.Column('cluster_id', sa.Text(), nullable=True),
    sa.Column('error_step', sa.Text(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('process_memory', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('process_runtime', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('progress_steps_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('products_exist_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('products_committed_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exposure_id'], ['exposures._id'], name='reports_exposure_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='reports_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_reports__id'), 'reports', ['_id'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_exposure_id'), 'reports', ['exposure_id'], unique=False)
    op.create_index(op.f('ix_reports_finish_time'), 'reports', ['finish_time'], unique=False)
    op.create_index(op.f('ix_reports_products_committed_bitflag'), 'reports', ['products_committed_bitflag'], unique=False)
    op.create_index(op.f('ix_reports_products_exist_bitflag'), 'reports', ['products_exist_bitflag'], unique=False)
    op.create_index(op.f('ix_reports_progress_steps_bitflag'), 'reports', ['progress_steps_bitflag'], unique=False)
    op.create_index(op.f('ix_reports_provenance_id'), 'reports', ['provenance_id'], unique=False)
    op.create_index(op.f('ix_reports_section_id'), 'reports', ['section_id'], unique=False)
    op.create_index(op.f('ix_reports_start_time'), 'reports', ['start_time'], unique=False)
    op.create_index(op.f('ix_reports_success'), 'reports', ['success'], unique=False)
    op.create_table('calibrator_files',
    sa.Column('_type', sa.SMALLINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('_calibrator_set', sa.SMALLINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('_flat_type', sa.SMALLINT(), nullable=True),
    sa.Column('instrument', sa.Text(), nullable=False),
    sa.Column('sensor_section', sa.Text(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('datafile_id', sa.UUID(), nullable=True),
    sa.Column('validity_start', sa.DateTime(), nullable=True),
    sa.Column('validity_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['datafile_id'], ['data_files._id'], name='calibrator_files_data_file_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images._id'], name='calibrator_files_image_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_calibrator_files__calibrator_set'), 'calibrator_files', ['_calibrator_set'], unique=False)
    op.create_index(op.f('ix_calibrator_files__flat_type'), 'calibrator_files', ['_flat_type'], unique=False)
    op.create_index(op.f('ix_calibrator_files__id'), 'calibrator_files', ['_id'], unique=False)
    op.create_index(op.f('ix_calibrator_files__type'), 'calibrator_files', ['_type'], unique=False)
    op.create_index(op.f('ix_calibrator_files_created_at'), 'calibrator_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_calibrator_files_datafile_id'), 'calibrator_files', ['datafile_id'], unique=False)
    op.create_index(op.f('ix_calibrator_files_image_id'), 'calibrator_files', ['image_id'], unique=False)
    op.create_index(op.f('ix_calibrator_files_instrument'), 'calibrator_files', ['instrument'], unique=False)
    op.create_index(op.f('ix_calibrator_files_sensor_section'), 'calibrator_files', ['sensor_section'], unique=False)
    op.create_index(op.f('ix_calibrator_files_validity_end'), 'calibrator_files', ['validity_end'], unique=False)
    op.create_index(op.f('ix_calibrator_files_validity_start'), 'calibrator_files', ['validity_start'], unique=False)
    op.create_table('source_lists',
    sa.Column('_format', sa.SMALLINT(), server_default=sa.text('2'), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('aper_rads', postgresql.ARRAY(sa.REAL(), zero_indexes=True), nullable=True),
    sa.Column('inf_aper_num', sa.SMALLINT(), nullable=True),
    sa.Column('best_aper_num', sa.SMALLINT(), nullable=True),
    sa.Column('num_sources', sa.Integer(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True),
    sa.Column('md5sum', sa.UUID(), nullable=True),
    sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_upstream_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('NOT(md5sum IS NULL AND (md5sum_components IS NULL OR array_position(md5sum_components, NULL) IS NOT NULL))', name='source_lists_md5sum_check'),
    sa.ForeignKeyConstraint(['image_id'], ['images._id'], name='source_lists_image_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='source_lists_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('image_id', 'provenance_id', name='_source_list_image_provenance_uc')
    )
    op.create_index(op.f('ix_source_lists__bitflag'), 'source_lists', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_source_lists__id'), 'source_lists', ['_id'], unique=False)
    op.create_index(op.f('ix_source_lists__upstream_bitflag'), 'source_lists', ['_upstream_bitflag'], unique=False)
    op.create_index(op.f('ix_source_lists_created_at'), 'source_lists', ['created_at'], unique=False)
    op.create_index(op.f('ix_source_lists_filepath'), 'source_lists', ['filepath'], unique=True)
    op.create_index(op.f('ix_source_lists_image_id'), 'source_lists', ['image_id'], unique=False)
    op.create_index(op.f('ix_source_lists_num_sources'), 'source_lists', ['num_sources'], unique=False)
    op.create_index(op.f('ix_source_lists_provenance_id'), 'source_lists', ['provenance_id'], unique=False)
    op.create_table('backgrounds',
    sa.Column('_format', sa.SMALLINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('_method', sa.SMALLINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('sources_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('noise', sa.Float(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True),
    sa.Column('md5sum', sa.UUID(), nullable=True),
    sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_upstream_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('NOT(md5sum IS NULL AND (md5sum_components IS NULL OR array_position(md5sum_components, NULL) IS NOT NULL))', name='backgrounds_md5sum_check'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='background_provenance_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sources_id'], ['source_lists._id'], name='backgrounds_source_lists_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('sources_id', 'provenance_id', name='_background_source_list_provenance_ud')
    )
    op.create_index(op.f('ix_backgrounds__bitflag'), 'backgrounds', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_backgrounds__id'), 'backgrounds', ['_id'], unique=False)
    op.create_index(op.f('ix_backgrounds__upstream_bitflag'), 'backgrounds', ['_upstream_bitflag'], unique=False)
    op.create_index(op.f('ix_backgrounds_created_at'), 'backgrounds', ['created_at'], unique=False)
    op.create_index(op.f('ix_backgrounds_filepath'), 'backgrounds', ['filepath'], unique=True)
    op.create_index(op.f('ix_backgrounds_noise'), 'backgrounds', ['noise'], unique=False)
    op.create_index(op.f('ix_backgrounds_provenance_id'), 'backgrounds', ['provenance_id'], unique=False)
    op.create_index(op.f('ix_backgrounds_sources_id'), 'backgrounds', ['sources_id'], unique=True)
    op.create_index(op.f('ix_backgrounds_value'), 'backgrounds', ['value'], unique=False)
    op.create_table('cutouts',
    sa.Column('_format', sa.SMALLINT(), server_default=sa.text('2'), nullable=False),
    sa.Column('sources_id', sa.UUID(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True),
    sa.Column('md5sum', sa.UUID(), nullable=True),
    sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_upstream_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('NOT(md5sum IS NULL AND (md5sum_components IS NULL OR array_position(md5sum_components, NULL) IS NOT NULL))', name='cutouts_md5sum_check'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='cutouts_provenance_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sources_id'], ['source_lists._id'], name='cutouts_source_list_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('sources_id', 'provenance_id', name='_cutouts_sources_provenance_uc')
    )
    op.create_index(op.f('ix_cutouts__bitflag'), 'cutouts', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_cutouts__id'), 'cutouts', ['_id'], unique=False)
    op.create_index(op.f('ix_cutouts__upstream_bitflag'), 'cutouts', ['_upstream_bitflag'], unique=False)
    op.create_index(op.f('ix_cutouts_created_at'), 'cutouts', ['created_at'], unique=False)
    op.create_index(op.f('ix_cutouts_filepath'), 'cutouts', ['filepath'], unique=True)
    op.create_index(op.f('ix_cutouts_provenance_id'), 'cutouts', ['provenance_id'], unique=False)
    op.create_index(op.f('ix_cutouts_sources_id'), 'cutouts', ['sources_id'], unique=False)
    op.create_table('psfs',
    sa.Column('_format', sa.SMALLINT(), server_default=sa.text('1'), nullable=False),
    sa.Column('sources_id', sa.UUID(), nullable=False),
    sa.Column('fwhm_pixels', sa.REAL(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True),
    sa.Column('md5sum', sa.UUID(), nullable=True),
    sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_upstream_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('NOT(md5sum IS NULL AND (md5sum_components IS NULL OR array_position(md5sum_components, NULL) IS NOT NULL))', name='psfs_md5sum_check'),
    sa.ForeignKeyConstraint(['sources_id'], ['source_lists._id'], name='psfs_source_lists_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_psfs__bitflag'), 'psfs', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_psfs__id'), 'psfs', ['_id'], unique=False)
    op.create_index(op.f('ix_psfs__upstream_bitflag'), 'psfs', ['_upstream_bitflag'], unique=False)
    op.create_index(op.f('ix_psfs_created_at'), 'psfs', ['created_at'], unique=False)
    op.create_index(op.f('ix_psfs_filepath'), 'psfs', ['filepath'], unique=True)
    op.create_index(op.f('ix_psfs_sources_id'), 'psfs', ['sources_id'], unique=True)
    op.create_table('world_coordinates',
    sa.Column('sources_id', sa.UUID(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('components', postgresql.ARRAY(sa.Text(), zero_indexes=True), nullable=True),
    sa.Column('md5sum', sa.UUID(), nullable=True),
    sa.Column('md5sum_components', postgresql.ARRAY(sa.UUID(), zero_indexes=True), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_upstream_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('NOT(md5sum IS NULL AND (md5sum_components IS NULL OR array_position(md5sum_components, NULL) IS NOT NULL))', name='world_coordinates_md5sum_check'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='wcs_provenance_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sources_id'], ['source_lists._id'], name='world_coordinates_source_list_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('sources_id', 'provenance_id', name='_wcs_source_list_provenance_uc')
    )
    op.create_index(op.f('ix_world_coordinates__bitflag'), 'world_coordinates', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_world_coordinates__id'), 'world_coordinates', ['_id'], unique=False)
    op.create_index(op.f('ix_world_coordinates__upstream_bitflag'), 'world_coordinates', ['_upstream_bitflag'], unique=False)
    op.create_index(op.f('ix_world_coordinates_created_at'), 'world_coordinates', ['created_at'], unique=False)
    op.create_index(op.f('ix_world_coordinates_filepath'), 'world_coordinates', ['filepath'], unique=True)
    op.create_index(op.f('ix_world_coordinates_provenance_id'), 'world_coordinates', ['provenance_id'], unique=False)
    op.create_index(op.f('ix_world_coordinates_sources_id'), 'world_coordinates', ['sources_id'], unique=True)
    op.create_table('measurements',
    sa.Column('cutouts_id', sa.UUID(), nullable=False),
    sa.Column('index_in_sources', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('flux_psf', sa.REAL(), nullable=False),
    sa.Column('flux_psf_err', sa.REAL(), nullable=False),
    sa.Column('flux_apertures', postgresql.ARRAY(sa.REAL(), zero_indexes=True), nullable=False),
    sa.Column('flux_apertures_err', postgresql.ARRAY(sa.REAL(), zero_indexes=True), nullable=False),
    sa.Column('bkg_per_pix', sa.REAL(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('aper_radii', postgresql.ARRAY(sa.REAL(), zero_indexes=True), nullable=False),
    sa.Column('best_aperture', sa.SMALLINT(), server_default=sa.text('-1'), nullable=False),
    sa.Column('center_x_pixel', sa.Integer(), nullable=False),
    sa.Column('center_y_pixel', sa.Integer(), nullable=False),
    sa.Column('x', sa.REAL(), nullable=False),
    sa.Column('y', sa.REAL(), nullable=False),
    sa.Column('gfit_x', sa.REAL(), nullable=False),
    sa.Column('gfit_y', sa.REAL(), nullable=False),
    sa.Column('major_width', sa.REAL(), nullable=False),
    sa.Column('minor_width', sa.REAL(), nullable=False),
    sa.Column('position_angle', sa.REAL(), nullable=False),
    sa.Column('psf_fit_flags', sa.Integer(), nullable=True),
    sa.Column('nbadpix', sa.Integer(), nullable=True),
    sa.Column('negfrac', sa.REAL(), nullable=True),
    sa.Column('negfluxfrac', sa.REAL(), nullable=True),
    sa.Column('is_bad', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('ra', sa.Double(), nullable=False),
    sa.Column('dec', sa.Double(), nullable=False),
    sa.Column('gallat', sa.Double(), nullable=True),
    sa.Column('gallon', sa.Double(), nullable=True),
    sa.Column('ecllat', sa.Double(), nullable=True),
    sa.Column('ecllon', sa.Double(), nullable=True),
    sa.Column('_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_upstream_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['cutouts_id'], ['cutouts._id'], name='measurements_cutouts_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id'], ['objects._id'], name='measurements_object_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='measurements_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('cutouts_id', 'index_in_sources', 'provenance_id', name='_measurements_cutouts_provenance_uc')
    )
    op.create_index(op.f('ix_measurements__bitflag'), 'measurements', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_measurements__id'), 'measurements', ['_id'], unique=False)
    op.create_index(op.f('ix_measurements__upstream_bitflag'), 'measurements', ['_upstream_bitflag'], unique=False)
    op.create_index(op.f('ix_measurements_created_at'), 'measurements', ['created_at'], unique=False)
    op.create_index(op.f('ix_measurements_cutouts_id'), 'measurements', ['cutouts_id'], unique=False)
    op.create_index(op.f('ix_measurements_ecllat'), 'measurements', ['ecllat'], unique=False)
    op.create_index(op.f('ix_measurements_gallat'), 'measurements', ['gallat'], unique=False)
    op.create_index(op.f('ix_measurements_is_bad'), 'measurements', ['is_bad'], unique=False)
    op.create_index(op.f('ix_measurements_object_id'), 'measurements', ['object_id'], unique=False)
    op.create_index(op.f('ix_measurements_provenance_id'), 'measurements', ['provenance_id'], unique=False)
    op.create_index('measurements_q3c_ang2ipix_idx', 'measurements', [sa.text('q3c_ang2ipix(ra, dec)')], unique=False)
    op.create_table('zero_points',
    sa.Column('wcs_id', sa.UUID(), nullable=False),
    sa.Column('background_id', sa.UUID(), nullable=False),
    sa.Column('zp', sa.REAL(), nullable=False),
    sa.Column('dzp', sa.REAL(), nullable=False),
    sa.Column('aper_cor_radii', postgresql.ARRAY(sa.REAL(), zero_indexes=True), nullable=True),
    sa.Column('aper_cors', postgresql.ARRAY(sa.REAL(), zero_indexes=True), nullable=True),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_upstream_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['background_id'], ['backgrounds._id'], name='zp_background_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='zp_provenance_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wcs_id'], ['world_coordinates._id'], name='zp_wcs_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('wcs_id', 'background_id', 'provenance_id', name='_zp_wcs_bg_provenance_uc')
    )
    op.create_index(op.f('ix_zero_points__bitflag'), 'zero_points', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_zero_points__id'), 'zero_points', ['_id'], unique=False)
    op.create_index(op.f('ix_zero_points__upstream_bitflag'), 'zero_points', ['_upstream_bitflag'], unique=False)
    op.create_index(op.f('ix_zero_points_background_id'), 'zero_points', ['background_id'], unique=False)
    op.create_index(op.f('ix_zero_points_created_at'), 'zero_points', ['created_at'], unique=False)
    op.create_index(op.f('ix_zero_points_provenance_id'), 'zero_points', ['provenance_id'], unique=False)
    op.create_index(op.f('ix_zero_points_wcs_id'), 'zero_points', ['wcs_id'], unique=False)
    op.create_table('deepscores',
    sa.Column('_algorithm', sa.SMALLINT(), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('measurements_id', sa.UUID(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('score', sa.REAL(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_upstream_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['measurements_id'], ['measurements._id'], name='deepscore_measurements_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='deepscore_provenance_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('measurements_id', '_algorithm', 'provenance_id', name='_algorithm_measurements_provenance_uc')
    )
    op.create_index(op.f('ix_deepscores__bitflag'), 'deepscores', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_deepscores__id'), 'deepscores', ['_id'], unique=False)
    op.create_index(op.f('ix_deepscores__upstream_bitflag'), 'deepscores', ['_upstream_bitflag'], unique=False)
    op.create_index(op.f('ix_deepscores_created_at'), 'deepscores', ['created_at'], unique=False)
    op.create_index(op.f('ix_deepscores_measurements_id'), 'deepscores', ['measurements_id'], unique=False)
    op.create_index(op.f('ix_deepscores_provenance_id'), 'deepscores', ['provenance_id'], unique=False)
    op.create_table('image_coadd_component',
    sa.Column('zp_id', sa.UUID(), nullable=False),
    sa.Column('coadd_image_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coadd_image_id'], ['images._id'], name='image_coadd_component_coadd_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zp_id'], ['zero_points._id'], name='image_coadd_component_zp_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('zp_id', 'coadd_image_id')
    )
    op.create_index(op.f('ix_image_coadd_component_coadd_image_id'), 'image_coadd_component', ['coadd_image_id'], unique=False)
    op.create_index(op.f('ix_image_coadd_component_zp_id'), 'image_coadd_component', ['zp_id'], unique=False)
    op.create_table('refs',
    sa.Column('zp_id', sa.UUID(), nullable=False),
    sa.Column('provenance_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_upstream_bitflag', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenances._id'], name='references_provenance_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zp_id'], ['zero_points._id'], name='references_zp_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_refs__bitflag'), 'refs', ['_bitflag'], unique=False)
    op.create_index(op.f('ix_refs__id'), 'refs', ['_id'], unique=False)
    op.create_index(op.f('ix_refs__upstream_bitflag'), 'refs', ['_upstream_bitflag'], unique=False)
    op.create_index(op.f('ix_refs_created_at'), 'refs', ['created_at'], unique=False)
    op.create_index(op.f('ix_refs_provenance_id'), 'refs', ['provenance_id'], unique=False)
    op.create_index(op.f('ix_refs_zp_id'), 'refs', ['zp_id'], unique=False)
    op.create_table('image_subtraction_components',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('new_zp_id', sa.UUID(), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images._id'], name='image_subtraction_sub_image_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_zp_id'], ['zero_points._id'], name='image_subtraction_new_zp_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ref_id'], ['refs._id'], name='image_subtraction_ref_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_image_subtraction_components_new_zp_id'), 'image_subtraction_components', ['new_zp_id'], unique=False)
    op.create_index(op.f('ix_image_subtraction_components_ref_id'), 'image_subtraction_components', ['ref_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_subtraction_components_ref_id'), table_name='image_subtraction_components')
    op.drop_index(op.f('ix_image_subtraction_components_new_zp_id'), table_name='image_subtraction_components')
    op.drop_table('image_subtraction_components')
    op.drop_index(op.f('ix_refs_zp_id'), table_name='refs')
    op.drop_index(op.f('ix_refs_provenance_id'), table_name='refs')
    op.drop_index(op.f('ix_refs_created_at'), table_name='refs')
    op.drop_index(op.f('ix_refs__upstream_bitflag'), table_name='refs')
    op.drop_index(op.f('ix_refs__id'), table_name='refs')
    op.drop_index(op.f('ix_refs__bitflag'), table_name='refs')
    op.drop_table('refs')
    op.drop_index(op.f('ix_image_coadd_component_zp_id'), table_name='image_coadd_component')
    op.drop_index(op.f('ix_image_coadd_component_coadd_image_id'), table_name='image_coadd_component')
    op.drop_table('image_coadd_component')
    op.drop_index(op.f('ix_deepscores_provenance_id'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores_measurements_id'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores_created_at'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores__upstream_bitflag'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores__id'), table_name='deepscores')
    op.drop_index(op.f('ix_deepscores__bitflag'), table_name='deepscores')
    op.drop_table('deepscores')
    op.drop_index(op.f('ix_zero_points_wcs_id'), table_name='zero_points')
    op.drop_index(op.f('ix_zero_points_provenance_id'), table_name='zero_points')
    op.drop_index(op.f('ix_zero_points_created_at'), table_name='zero_points')
    op.drop_index(op.f('ix_zero_points_background_id'), table_name='zero_points')
    op.drop_index(op.f('ix_zero_points__upstream_bitflag'), table_name='zero_points')
    op.drop_index(op.f('ix_zero_points__id'), table_name='zero_points')
    op.drop_index(op.f('ix_zero_points__bitflag'), table_name='zero_points')
    op.drop_table('zero_points')
    op.drop_index('measurements_q3c_ang2ipix_idx', table_name='measurements')
    op.drop_index(op.f('ix_measurements_provenance_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_object_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_is_bad'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_gallat'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_ecllat'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_cutouts_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_created_at'), table_name='measurements')
    op.drop_index(op.f('ix_measurements__upstream_bitflag'), table_name='measurements')
    op.drop_index(op.f('ix_measurements__id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements__bitflag'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_world_coordinates_sources_id'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates_provenance_id'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates_filepath'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates_created_at'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates__upstream_bitflag'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates__id'), table_name='world_coordinates')
    op.drop_index(op.f('ix_world_coordinates__bitflag'), table_name='world_coordinates')
    op.drop_table('world_coordinates')
    op.drop_index(op.f('ix_psfs_sources_id'), table_name='psfs')
    op.drop_index(op.f('ix_psfs_filepath'), table_name='psfs')
    op.drop_index(op.f('ix_psfs_created_at'), table_name='psfs')
    op.drop_index(op.f('ix_psfs__upstream_bitflag'), table_name='psfs')
    op.drop_index(op.f('ix_psfs__id'), table_name='psfs')
    op.drop_index(op.f('ix_psfs__bitflag'), table_name='psfs')
    op.drop_table('psfs')
    op.drop_index(op.f('ix_cutouts_sources_id'), table_name='cutouts')
    op.drop_index(op.f('ix_cutouts_provenance_id'), table_name='cutouts')
    op.drop_index(op.f('ix_cutouts_filepath'), table_name='cutouts')
    op.drop_index(op.f('ix_cutouts_created_at'), table_name='cutouts')
    op.drop_index(op.f('ix_cutouts__upstream_bitflag'), table_name='cutouts')
    op.drop_index(op.f('ix_cutouts__id'), table_name='cutouts')
    op.drop_index(op.f('ix_cutouts__bitflag'), table_name='cutouts')
    op.drop_table('cutouts')
    op.drop_index(op.f('ix_backgrounds_value'), table_name='backgrounds')
    op.drop_index(op.f('ix_backgrounds_sources_id'), table_name='backgrounds')
    op.drop_index(op.f('ix_backgrounds_provenance_id'), table_name='backgrounds')
    op.drop_index(op.f('ix_backgrounds_noise'), table_name='backgrounds')
    op.drop_index(op.f('ix_backgrounds_filepath'), table_name='backgrounds')
    op.drop_index(op.f('ix_backgrounds_created_at'), table_name='backgrounds')
    op.drop_index(op.f('ix_backgrounds__upstream_bitflag'), table_name='backgrounds')
    op.drop_index(op.f('ix_backgrounds__id'), table_name='backgrounds')
    op.drop_index(op.f('ix_backgrounds__bitflag'), table_name='backgrounds')
    op.drop_table('backgrounds')
    op.drop_index(op.f('ix_source_lists_provenance_id'), table_name='source_lists')
    op.drop_index(op.f('ix_source_lists_num_sources'), table_name='source_lists')
    op.drop_index(op.f('ix_source_lists_image_id'), table_name='source_lists')
    op.drop_index(op.f('ix_source_lists_filepath'), table_name='source_lists')
    op.drop_index(op.f('ix_source_lists_created_at'), table_name='source_lists')
    op.drop_index(op.f('ix_source_lists__upstream_bitflag'), table_name='source_lists')
    op.drop_index(op.f('ix_source_lists__id'), table_name='source_lists')
    op.drop_index(op.f('ix_source_lists__bitflag'), table_name='source_lists')
    op.drop_table('source_lists')
    op.drop_index(op.f('ix_calibrator_files_validity_start'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files_validity_end'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files_sensor_section'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files_instrument'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files_image_id'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files_datafile_id'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files_created_at'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files__type'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files__id'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files__flat_type'), table_name='calibrator_files')
    op.drop_index(op.f('ix_calibrator_files__calibrator_set'), table_name='calibrator_files')
    op.drop_table('calibrator_files')
    op.drop_index(op.f('ix_reports_success'), table_name='reports')
    op.drop_index(op.f('ix_reports_start_time'), table_name='reports')
    op.drop_index(op.f('ix_reports_section_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_provenance_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_progress_steps_bitflag'), table_name='reports')
    op.drop_index(op.f('ix_reports_products_exist_bitflag'), table_name='reports')
    op.drop_index(op.f('ix_reports_products_committed_bitflag'), table_name='reports')
    op.drop_index(op.f('ix_reports_finish_time'), table_name='reports')
    op.drop_index(op.f('ix_reports_exposure_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports__id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('knownexposures_q3c_ang2ipix_idx', table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_mjd'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_instrument'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_identifier'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_gallat'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_ecllat'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures_created_at'), table_name='knownexposures')
    op.drop_index(op.f('ix_knownexposures__id'), table_name='knownexposures')
    op.drop_table('knownexposures')
    op.drop_index(op.f('ix_images_zero_point_estimate'), table_name='images')
    op.drop_index(op.f('ix_images_telescope'), table_name='images')
    op.drop_index(op.f('ix_images_target'), table_name='images')
    op.drop_index(op.f('ix_images_section_id'), table_name='images')
    op.drop_index(op.f('ix_images_ra_corner_11'), table_name='images')
    op.drop_index(op.f('ix_images_ra_corner_10'), table_name='images')
    op.drop_index(op.f('ix_images_ra_corner_01'), table_name='images')
    op.drop_index(op.f('ix_images_ra_corner_00'), table_name='images')
    op.drop_index(op.f('ix_images_provenance_id'), table_name='images')
    op.drop_index(op.f('ix_images_project'), table_name='images')
    op.drop_index(op.f('ix_images_mjd'), table_name='images')
    op.drop_index(op.f('ix_images_minra'), table_name='images')
    op.drop_index(op.f('ix_images_mindec'), table_name='images')
    op.drop_index(op.f('ix_images_maxra'), table_name='images')
    op.drop_index(op.f('ix_images_maxdec'), table_name='images')
    op.drop_index(op.f('ix_images_lim_mag_estimate'), table_name='images')
    op.drop_index(op.f('ix_images_is_sub'), table_name='images')
    op.drop_index(op.f('ix_images_is_coadd'), table_name='images')
    op.drop_index(op.f('ix_images_instrument'), table_name='images')
    op.drop_index(op.f('ix_images_gallat'), table_name='images')
    op.drop_index(op.f('ix_images_fwhm_estimate'), table_name='images')
    op.drop_index(op.f('ix_images_filter'), table_name='images')
    op.drop_index(op.f('ix_images_filepath'), table_name='images')
    op.drop_index(op.f('ix_images_exposure_id'), table_name='images')
    op.drop_index(op.f('ix_images_exp_time'), table_name='images')
    op.drop_index(op.f('ix_images_end_mjd'), table_name='images')
    op.drop_index(op.f('ix_images_ecllat'), table_name='images')
    op.drop_index(op.f('ix_images_dec_corner_11'), table_name='images')
    op.drop_index(op.f('ix_images_dec_corner_10'), table_name='images')
    op.drop_index(op.f('ix_images_dec_corner_01'), table_name='images')
    op.drop_index(op.f('ix_images_dec_corner_00'), table_name='images')
    op.drop_index(op.f('ix_images_created_at'), table_name='images')
    op.drop_index(op.f('ix_images_coadd_alignment_target'), table_name='images')
    op.drop_index(op.f('ix_images_bkg_rms_estimate'), table_name='images')
    op.drop_index(op.f('ix_images_bkg_mean_estimate'), table_name='images')
    op.drop_index(op.f('ix_images_airmass'), table_name='images')
    op.drop_index(op.f('ix_images__upstream_bitflag'), table_name='images')
    op.drop_index(op.f('ix_images__type'), table_name='images')
    op.drop_index(op.f('ix_images__id'), table_name='images')
    op.drop_index(op.f('ix_images__bitflag'), table_name='images')
    op.drop_index('images_q3c_ang2ipix_idx', table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_refsets_provenance_id'), table_name='refsets')
    op.drop_index(op.f('ix_refsets_name'), table_name='refsets')
    op.drop_index(op.f('ix_refsets_created_at'), table_name='refsets')
    op.drop_index(op.f('ix_refsets__id'), table_name='refsets')
    op.drop_table('refsets')
    op.drop_table('provenance_upstreams')
    op.drop_index(op.f('ix_provenance_tags_tag'), table_name='provenance_tags')
    op.drop_index(op.f('ix_provenance_tags_provenance_id'), table_name='provenance_tags')
    op.drop_index(op.f('ix_provenance_tags_created_at'), table_name='provenance_tags')
    op.drop_index(op.f('ix_provenance_tags__id'), table_name='provenance_tags')
    op.drop_table('provenance_tags')
    op.drop_index(op.f('ix_exposures_target'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_provenance_id'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_project'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_origin_identifier'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_mjd'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_instrument'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_gallat'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_filter_array'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_filepath'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_exp_time'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_ecllat'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_created_at'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_airmass'), table_name='exposures')
    op.drop_index(op.f('ix_exposures__type'), table_name='exposures')
    op.drop_index(op.f('ix_exposures__id'), table_name='exposures')
    op.drop_index(op.f('ix_exposures__filter'), table_name='exposures')
    op.drop_index(op.f('ix_exposures__bitflag'), table_name='exposures')
    op.drop_index('exposures_q3c_ang2ipix_idx', table_name='exposures')
    op.drop_table('exposures')
    op.drop_index(op.f('ix_data_files_provenance_id'), table_name='data_files')
    op.drop_index(op.f('ix_data_files_filepath'), table_name='data_files')
    op.drop_index(op.f('ix_data_files_created_at'), table_name='data_files')
    op.drop_index(op.f('ix_data_files__id'), table_name='data_files')
    op.drop_table('data_files')
    op.drop_index(op.f('ix_provenances_replaced_by'), table_name='provenances')
    op.drop_index(op.f('ix_provenances_process'), table_name='provenances')
    op.drop_index(op.f('ix_provenances_created_at'), table_name='provenances')
    op.drop_index(op.f('ix_provenances_code_version_id'), table_name='provenances')
    op.drop_table('provenances')
    op.drop_index(op.f('ix_passwordlink_userid'), table_name='passwordlink')
    op.drop_index(op.f('ix_passwordlink_created_at'), table_name='passwordlink')
    op.drop_table('passwordlink')
    op.drop_index(op.f('ix_code_hashes_created_at'), table_name='code_hashes')
    op.drop_index(op.f('ix_code_hashes_code_version_id'), table_name='code_hashes')
    op.drop_table('code_hashes')
    op.drop_index(op.f('ix_sensor_sections_validity_start'), table_name='sensor_sections')
    op.drop_index(op.f('ix_sensor_sections_validity_end'), table_name='sensor_sections')
    op.drop_index(op.f('ix_sensor_sections_instrument'), table_name='sensor_sections')
    op.drop_index(op.f('ix_sensor_sections_identifier'), table_name='sensor_sections')
    op.drop_index(op.f('ix_sensor_sections_defective'), table_name='sensor_sections')
    op.drop_index(op.f('ix_sensor_sections_created_at'), table_name='sensor_sections')
    op.drop_index(op.f('ix_sensor_sections__id'), table_name='sensor_sections')
    op.drop_table('sensor_sections')
    op.drop_index(op.f('ix_pipelineworkers_created_at'), table_name='pipelineworkers')
    op.drop_index(op.f('ix_pipelineworkers__id'), table_name='pipelineworkers')
    op.drop_table('pipelineworkers')
    op.drop_index('objects_q3c_ang2ipix_idx', table_name='objects')
    op.drop_index(op.f('ix_objects_name'), table_name='objects')
    op.drop_index(op.f('ix_objects_is_bad'), table_name='objects')
    op.drop_index(op.f('ix_objects_gallat'), table_name='objects')
    op.drop_index(op.f('ix_objects_ecllat'), table_name='objects')
    op.drop_index(op.f('ix_objects_created_at'), table_name='objects')
    op.drop_index(op.f('ix_objects__id'), table_name='objects')
    op.drop_table('objects')
    op.drop_index(op.f('ix_gaiadr3_downloadlock_created_at'), table_name='gaiadr3_downloadlock')
    op.drop_index(op.f('ix_gaiadr3_downloadlock__id'), table_name='gaiadr3_downloadlock')
    op.drop_table('gaiadr3_downloadlock')
    op.drop_index(op.f('ix_code_versions_created_at'), table_name='code_versions')
    op.drop_table('code_versions')
    op.drop_index(op.f('ix_catalog_excerpts_ra_corner_11'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_ra_corner_10'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_ra_corner_01'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_ra_corner_00'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_num_items'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_minra'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_minmag'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_mindec'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_maxra'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_maxmag'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_maxdec'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_gallat'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_filepath'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_ecllat'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_dec_corner_11'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_dec_corner_10'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_dec_corner_01'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_dec_corner_00'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts_created_at'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts__origin'), table_name='catalog_excerpts')
    op.drop_index(op.f('ix_catalog_excerpts__id'), table_name='catalog_excerpts')
    op.drop_index('catalog_excerpts_q3c_ang2ipix_idx', table_name='catalog_excerpts')
    op.drop_table('catalog_excerpts')
    op.drop_index(op.f('ix_calibfile_downloadlock_created_at'), table_name='calibfile_downloadlock')
    op.drop_index(op.f('ix_calibfile_downloadlock__id'), table_name='calibfile_downloadlock')
    op.drop_table('calibfile_downloadlock')
    op.drop_index(op.f('ix_authuser_username'), table_name='authuser')
    op.drop_index(op.f('ix_authuser_email'), table_name='authuser')
    op.drop_index(op.f('ix_authuser_created_at'), table_name='authuser')
    op.drop_table('authuser')
    # ### end Alembic commands ###
