"""initial

Revision ID: 9f546bde906b
Revises: 
Create Date: 2023-03-30 20:54:06.716947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f546bde906b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_versions',
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_versions_created_at'), 'code_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_code_versions_id'), 'code_versions', ['id'], unique=False)
    op.create_index(op.f('ix_code_versions_version'), 'code_versions', ['version'], unique=True)
    op.create_table('code_hashes',
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('code_version_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code_version_id'], ['code_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_hashes_created_at'), 'code_hashes', ['created_at'], unique=False)
    op.create_index(op.f('ix_code_hashes_hash'), 'code_hashes', ['hash'], unique=True)
    op.create_index(op.f('ix_code_hashes_id'), 'code_hashes', ['id'], unique=False)
    op.create_table('provenances',
    sa.Column('process', sa.String(), nullable=False),
    sa.Column('code_version_id', sa.Integer(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unique_hash', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code_version_id'], ['code_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provenances_code_version_id'), 'provenances', ['code_version_id'], unique=False)
    op.create_index(op.f('ix_provenances_created_at'), 'provenances', ['created_at'], unique=False)
    op.create_index(op.f('ix_provenances_id'), 'provenances', ['id'], unique=False)
    op.create_index(op.f('ix_provenances_process'), 'provenances', ['process'], unique=False)
    op.create_index(op.f('ix_provenances_unique_hash'), 'provenances', ['unique_hash'], unique=True)
    op.create_table('provenance_upstreams',
    sa.Column('upstream_id', sa.Integer(), nullable=False),
    sa.Column('downstream_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['downstream_id'], ['provenances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upstream_id'], ['provenances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upstream_id', 'downstream_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provenance_upstreams')
    op.drop_index(op.f('ix_provenances_unique_hash'), table_name='provenances')
    op.drop_index(op.f('ix_provenances_process'), table_name='provenances')
    op.drop_index(op.f('ix_provenances_id'), table_name='provenances')
    op.drop_index(op.f('ix_provenances_created_at'), table_name='provenances')
    op.drop_index(op.f('ix_provenances_code_version_id'), table_name='provenances')
    op.drop_table('provenances')
    op.drop_index(op.f('ix_code_hashes_id'), table_name='code_hashes')
    op.drop_index(op.f('ix_code_hashes_hash'), table_name='code_hashes')
    op.drop_index(op.f('ix_code_hashes_created_at'), table_name='code_hashes')
    op.drop_table('code_hashes')
    op.drop_index(op.f('ix_code_versions_version'), table_name='code_versions')
    op.drop_index(op.f('ix_code_versions_id'), table_name='code_versions')
    op.drop_index(op.f('ix_code_versions_created_at'), table_name='code_versions')
    op.drop_table('code_versions')
    # ### end Alembic commands ###
